repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: end-of-file-fixer
    - id: no-commit-to-branch
      args: [--branch, main]
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.12.0
  hooks:
    - id: helm-docs
