{{/* vim: set filetype=mustache: */}}

{{/*
Output lifecycle hook

If the AWS ALB preStopDelay flag is enabled, we add an additional sleep to
delay the container shutdown.

This allows the AWS ALB to fully de-register the pod before the container is
shutdown and helps achieve zero downtime rollouts.

Note, this cannot be used in conjunction with a custom lifecycle rule.
*/}}
{{- define "mintel_common.deployment.lifecycle" -}}
{{- with .Values.ingress }}
{{- if (and .enabled (and .alb.enabled .alb.preStopDelay.enabled )) }}
lifecycle:
  preStop:
    exec:
      command:
        - '/bin/sh'
        - '-c'
        - {{ printf "echo 'Called preStop hook with %ds delay' > /proc/1/fd/1 ; sleep %d ; echo 'Completed preStop hook'" (.alb.preStopDelay.delaySeconds|int) (.alb.preStopDelay.delaySeconds|int) }}
{{- else }}
{{- if $.Values.lifecycle }}
lifecycle:
{{ toYaml $.Values.lifecycle | nindent 10 }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}
