{{/* vim: set filetype=mustache: */}}

{{/* Output ingressClassName */}}
{{- define "mintel_common.ingress.className" -}}
{{- if (and .Values.ingress.alb .Values.ingress.alb.enabled) }}
{{- if eq .Values.ingress.alb.scheme "internet-facing" }}
{{- print "alb-public-apps-default" -}}
{{- end }}
{{- if eq .Values.ingress.alb.scheme "internal" }}
{{- print "alb-internal-apps-default" -}}
{{- end }}
{{- else }}
{{- print "haproxy" -}}
{{- end }}
{{- end -}}

{{/* Validate ALB BackendProtocol and default to HTTP */}}
{{- define "mintel_common.ingress.alb.backendProtocol" -}}
{{- if has .backendProtocol (list "HTTP" "HTTPS" ) }}
{{- .backendProtocol }}
{{- else }}
{{- "HTTP" }}
{{- end }}
{{- end }}

{{/* Validate ALB BackendProtocolVersion and default to HTTP1 */}}
{{- define "mintel_common.ingress.alb.backendProtocolVersion" -}}
{{- if has .backendProtocolVersion (list "HTTP1" "HTTP2" "GRPC" ) }}
{{- .backendProtocolVersion }}
{{- else }}
{{- "HTTP1" }}
{{- end }}
{{- end }}

{{/* Set default ALB healthcheck success-codes */}}
{{- define "mintel_common.ingress.alb.healthcheck.successCodes" -}}
{{- if eq .backendProtocolVersion "GRPC"}}
{{- default "0,12" .healthcheck.successCodes }}
{{- else }}
{{- default "200" .healthcheck.successCodes }}
{{- end }}
{{- end }}

{{/* Set default ALB healthcheck path */}}
{{- define "mintel_common.ingress.alb.healthcheck.path" -}}
{{- if eq .backendProtocolVersion "GRPC"}}
{{- default "/grpc.health.v1.Health/Check" .healthcheck.path }}
{{- else }}
{{- default "/readiness" .healthcheck.path }}
{{- end }}
{{- end }}

{{/* Set default ALB healthcheck port */}}
{{- define "mintel_common.ingress.alb.healthcheck.port" -}}
{{- if .Values.oauthProxy.enabled }}
{{- default 4180 .Values.ingress.alb.healthcheck.port }}
{{- else }}
{{- default .Values.port .Values.ingress.alb.healthcheck.port }}
{{- end }}
{{- end }}

{{/* Set default ALB healthcheck protocol */}}
{{- define "mintel_common.ingress.alb.healthcheck.protocol" -}}
{{- if has .healthcheck.protocol (list "HTTP" "HTTPS" ) }}
{{- .healthcheck.protocol}}
{{- else }}
{{- "HTTP" }}
{{- end }}
{{- end }}
