{{/* vim: set filetype=mustache: */}}

{{/*
Return true if any of the otel instrumentation frameworks have been enabled
*/}}
{{- define "mintel_common.instrumentation.enabled"  -}}
{{- with .Values.otelInstrumentation -}}
{{ .injectPython.enabled | or .injectJava.enabled | or .injectNodeJS.enabled | or .injectDotNet.enabled }}
{{- end -}}
{{- end -}}
