{{/* vim: set filetype=mustache: */}}

{{/*
Helpers for Keda objects
*/}}

{{- define "mintel_common.keda.scaledObject.cooldownPeriod" -}}
{{- max 60 .cooldownPeriod }}
{{- end }}

# maxReplicaCount must be <= 10
{{- define "mintel_common.keda.scaledObject.maxReplicaCount" -}}
{{- if (gt ( .maxReplicaCount | int) 10) }}
{{- 10 }}
{{- else }}
{{- max 1 .maxReplicaCount }}
{{- end }}
{{- end }}

# minReplicaCount must be >= 1
{{- define "mintel_common.keda.scaledObject.minReplicaCount" -}}
{{- max 1 .minReplicaCount}}
{{- end }}

# pollingInterval must be >= than 10
{{- define "mintel_common.keda.scaledObject.pollingInterval" -}}
{{- max 10 .pollingInterval}}
{{- end }}
