{{/* vim: set filetype=mustache: */}}

{{/*
Helpers for NLB LoadBalancer services
*/}}

{{ define "mintel_common.nlb.annotations" -}}
external-dns.alpha.kubernetes.io/ttl: "60"
external-dns.alpha.kubernetes.io/hostname: {{ .Values.nlb.defaultHost }}
service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .Values.nlb.scheme }}
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: {{ .Values.nlb.targetType }}
service.beta.kubernetes.io/healthcheck-path: {{ include "mintel_common.nlb.healthcheck.path" .Values.nlb }}
service.beta.kubernetes.io/healthcheck-port: "{{ include "mintel_common.nlb.healthcheck.port" . }}"
service.beta.kubernetes.io/healthcheck-protocol: {{ include "mintel_common.nlb.healthcheck.protocol" .Values.nlb }}
service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "{{ .Values.nlb.healthcheck.timeoutSeconds | default 5 }}"
service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "{{ .Values.nlb.healthcheck.intervalSeconds | default 10 }}"
service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "{{ .Values.nlb.healthcheck.healthyThresholdCount | default 2 }}"
service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "{{ .Values.nlb.healthcheck.unhealthyThresholdCount | default 2 }}"
{{- end }}

{{/* Set default NLB healthcheck path */}}
{{- define "mintel_common.nlb.healthcheck.path" -}}
{{- .healthcheck.path | default "/" }}
{{- end }}

{{/* Set default NLB healthcheck port */}}
{{- define "mintel_common.nlb.healthcheck.port" -}}
{{- if .Values.oauthProxy.enabled }}
{{- .Values.nlb.healthcheck.port | default 4180 }}
{{- else }}
{{- .Values.nlb.healthcheck.port | default .Values.port }}
{{- end }}
{{- end }}

{{/* Set default NLB healthcheck protocol */}}
{{- define "mintel_common.nlb.healthcheck.protocol" -}}
{{- if (list "HTTP" "HTTPS" "TCP") | has .healthcheck.protocol -}}
{{- .healthcheck.protocol -}}
{{- else -}}
TCP
{{- end -}}
{{- end -}}
