{{/* vim: set filetype=mustache: */}}

{{/*
Template for creating a ServiceAccount. Expects a list [$, config] as context where "config" is a dict containing the
following optional kwargs:

annotations:                  dict    # Any extra custom annotations.
argo:                         dict    # Standard argo object (processed by mintel_common.argoAnnotations).
automountServiceAccountToken: bool    # Whether to enable automountServiceAccountToken. Defaults to true.
irsa:                         dict    # Standard irsa object.
name:                         string  # The name of the service account. Defaults to global name if not provided.

*/}}
{{- define "mintel_common.serviceAccount" -}}
{{ $ := index . 0 }}
{{ $config := index . 1}}
apiVersion: {{ include "common.capabilities.serviceaccount.apiVersion" $ }}
kind: ServiceAccount
metadata:
  name: {{ $config.name | default (include "mintel_common.fullname" $) }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "mintel_common.labels" $ | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" $ | nindent 4 }}
    {{ if $config.annotations }}{{ $config.annotations | toYaml | nindent 4 }}{{ end }}
    {{ if (and $config.irsa.enabled (ne $.Values.global.clusterEnv "local")) }}
    {{ if $.Values.global.terraform.irsa }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ $.Values.global.cloudProvider.accountId }}:role/app-iam-{{ $.Values.global.clusterName }}-{{ $.Release.Namespace }}-{{ coalesce $config.irsa.nameOverride $config.name (include "mintel_common.fullname" $) }}
    {{- else }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ $.Values.global.cloudProvider.accountId }}:role/{{ $.Values.global.clusterName }}-{{ $.Release.Namespace }}-{{ coalesce $config.irsa.nameOverride $config.name (include "mintel_common.fullname" $) }}
    {{- end }}
    {{- end }}
    {{ if $config.argo }}
    {{ include "mintel_common.argoAnnotations" $config.argo | nindent 4 }}
    {{ end }}
automountServiceAccountToken: {{ $config.automountServiceAccountToken | default true }}
{{- end -}}
