apiVersion: v2
name: standard-application-stack
description: A generic chart to support most common application requirements

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 5.9.4

dependencies:
  - name: redis
    condition: (and redis.enabled (eq global.clusterEnv "local"))
    version: 16.11.2
    repository: https://charts.bitnami.com/bitnami
    tags:
      - localRedis
  - name: mariadb
    condition: (and mariadb.enabled (eq global.clusterEnv "local"))
    version: 11.0.10
    repository: https://charts.bitnami.com/bitnami
    tags:
      - localMariadb
  - name: postgresql
    condition: (and postgresql.enabled (eq global.clusterEnv "local"))
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    tags:
      - localPostgresql
  - name: mailhog
    condition: (and mailhog.enabled (eq global.clusterEnv "local"))
    version: 4.1.0
    repository: https://codecentric.github.io/helm-charts
    tags:
      - localMailhog
  - name: kibana
    condition: (and kibana.enabled (eq global.clusterEnv "local"))
    version: 7.5.2
    repository: https://helm.elastic.co
    tags:
      - localKibana
  - name: elasticsearch
    condition: (and elasticsearch.enabled (eq global.clusterEnv "local"))
    version: 7.5.2
    repository: https://helm.elastic.co
    tags:
      - localElasticsearch
  - name: opensearch
    condition: (and opensearch.enabled (eq global.clusterEnv "local"))
    version: 1.4.2
    repository: https://opensearch-project.github.io/helm-charts
    tags:
      - localOpensearch
  - name: opensearch-dashboards
    condition: (and opensearch.enabled (eq global.clusterEnv "local"))
    version: 1.0.8
    repository: https://opensearch-project.github.io/helm-charts
    tags:
      - localOpensearch
  - name: localstack
    condition: (and localstack.enabled (eq global.clusterEnv "local"))
    version: 0.3.5
    repository: https://localstack.github.io/helm-charts
    tags:
      - localLocalstack
