apiVersion: v2
name: aws-api-gateway-operator
description: AWS API Gateway Operator Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: v1.0.0
keywords:
  - eks
  - aws
  - api gateway
