{{- range $instanceName, $instanceCfg := default ( dict "default" dict ) .Values.postgresql.terraform.instances }}
  # Set name if not provided
  {{- if not ( hasKey $instanceCfg "name" ) }}
    {{- if eq $instanceName "default" }}
      {{- $_ := set $instanceCfg "name" $.Values.global.name }}
    {{- else }}
      {{- $_ := set $instanceCfg "name" $instanceName }}
    {{- end }}
  {{- end }}
  # Set db_name if not provided
  {{- if not ( hasKey $instanceCfg "db_name" ) }}
    {{- $_ := set $instanceCfg "db_name" ( $instanceCfg.name | replace "-" "_" | replace "." "_" ) }}
  {{- end }}
  # Add default values to each instance if keys not set already
  {{- range $defaultKey, $defaultVal := $.Values.postgresql.terraform.defaultVars }}
    {{- if not ( hasKey $instanceCfg $defaultKey ) }}
      {{- $_ := set $instanceCfg $defaultKey $defaultVal }}
    {{- end }}
  {{- end }}
---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: "postgres-{{ .name }}"
  namespace: {{ $.Release.Namespace | quote }}
spec:
  agentPoolID: "aws_{{ $.Values.global.clusterEnv }}"
  module:
    source: {{ $.Values.postgresql.terraform.module.source | quote }}
    version: {{ $.Values.postgresql.terraform.module.version | quote }}
  organization: {{ $.Values.global.terraform.organization | quote }}
  secretsMountPath: {{ $.Values.global.terraform.secretsMountPath | quote }}
  sshKeyID: "mintel-ssh"
  terraformVersion: {{ $.Values.global.terraform.version | quote }}
  variables:
  {{- range $varKey, $varVal := $instanceCfg }}
  - key: {{ $varKey }}
    environmentVariable: false
    hcl: false
    sensitive: false
    value: {{ $varVal | quote }}
  {{- end }}
{{- end }}
