{{- if .Values.s3.enabled }}
  {{- range $instanceName, $instanceCfg := default ( dict "default" dict ) .Values.s3.terraform.instances }}
    {{- $resource := "s3"}}
    {{- $moduleSource := $.Values.s3.terraform.module.source }}
    {{- $moduleVersion := $.Values.s3.terraform.module.version }}
    # Set name if not provided
    {{- if not ( hasKey $instanceCfg "name" ) }}
      {{- if eq $instanceName "default" }}
        {{- $_ := set $instanceCfg "name" $.Values.global.name }}
      {{- else }}
        {{- $_ := set $instanceCfg "name" $instanceName }}
      {{- end }}
    {{- end }}
    # Add default values to each instance if keys not set already
    {{- range $defaultKey, $defaultVal := $.Values.s3.terraform.defaultVars }}
      {{- if not ( hasKey $instanceCfg $defaultKey ) }}
        {{- $_ := set $instanceCfg $defaultKey $defaultVal }}
      {{- end }}
    {{- end }}
---
    {{- include "mintel_common.workspace" (list $ . $instanceCfg $resource $moduleSource $moduleVersion) }}
  {{- end }}
{{- end }}
