{{- if .Values.global.terraform.externalSecrets }}
  {{- range include "mintel_common.terraformCloudResources" $ | split "," }}
    {{- $global := $.Values.global }}
    {{- $resourceType := . }}
    {{- $resourceConfig := (get $.Values .) }}
    {{- if ( and $resourceConfig.enabled $resourceConfig.outputSecret) }}
      {{- range $instanceName, $instanceConfig := default ( dict "default" dict ) $resourceConfig.terraform.instances }}
        # Set instance.name via helper
        {{- $instanceDict := dict "Global" $global "InstanceCfg" $instanceConfig "InstanceName" $instanceName "ResourceType" $resourceType }}
        {{- $_ := set $instanceConfig "name" (include "mintel_common.terraform_cloud.instanceConfigName" $instanceDict | trim)}}
        {{- if not (hasKey $instanceConfig "output_secret_name") }}
          {{- $_ := set $instanceConfig "output_secret_name" ( printf "%s/%s/%s" $.Release.Namespace $instanceConfig.name $resourceType ) }}
        {{ end }}
        # Add default values to each instance if keys not set already
        {{- range $defaultKey, $defaultVal := $resourceConfig.terraform.defaultVars }}
          {{- if not ( hasKey $instanceConfig $defaultKey ) }}
            {{- $_ := set $instanceConfig $defaultKey $defaultVal }}
          {{- end }}
        {{- end }}
---
        {{- include "mintel_common.terraform_cloud.workspaceOutputSecret" (list $ . $instanceConfig $resourceType ) }}
      {{- end }}
    {{- end }}
  {{- end }}
# Below is a special case for when an app doesn't support IRSA (with possibly other use-cases down the line). If you
# define an output_secret_name in the irsa values it will create an ExternalSecret for the resulting Secrets Manager
# secret that the app-iam module creates.
---
  {{- if $.Values.irsa.terraform.vars.output_secret_name }}
    {{- $instanceConfig := $.Values.irsa.terraform.vars }}
    {{- $resourceType := "irsa" }}
    {{- include "mintel_common.terraform_cloud.workspaceOutputSecret" (list $ ( dict "name" $instanceConfig.name ) $instanceConfig $resourceType) }}
  {{- end }}
{{- end }}
