{{- if .Values.global.terraform.externalSecrets }}
{{- range include "mintel_common.terraformCloudResources" $ | split "," }}
  {{- $global := $.Values.global }}
  {{- $resourceType := . }}
  {{- $resourceConfig := (get $.Values .) }}
  {{- if ( and $resourceConfig.enabled $resourceConfig.outputSecret) }}
    {{- range $instanceName, $instanceConfig := default ( dict "default" dict ) $resourceConfig.terraform.instances }}
      # Set instance.name via helper
      {{- $instanceDict := dict "Global" $global "InstanceCfg" $instanceConfig "InstanceName" $instanceName "ResourceType" $resourceType }}
      {{- $_ := set $instanceConfig "name" (include "mintel_common.terraform_cloud.instanceConfigName" $instanceDict | trim)}}
      {{- if not (hasKey $instanceConfig "output_secret_name") }}
        {{- $_ := set $instanceConfig "output_secret_name" ( printf "%s/%s/%s" $.Release.Namespace $instanceConfig.name $resourceType ) }}
      {{ end }}
---
      {{- include "mintel_common.terraform_cloud.workspaceOutputSecret" (list $ . $instanceConfig $resourceType ) }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
