{{- if .Values.global.terraform.externalSecrets }}
{{- range include "mintel_common.terraformCloudResources" $ | split "," }}
  {{- $global := $.Values.global }}
  {{- $resourceType := . }}
  {{- $resourceConfig := (get $.Values .) }}
  {{- if $resourceConfig.enabled }}
    {{- range $instanceName, $instanceConfig := default ( dict "default" dict ) $resourceConfig.terraform.instances }}
      # Set name if not provided
      {{- if not ( hasKey $instanceConfig "name" ) }}
        {{- if eq $instanceName "default" }}
          {{- $_ := set $instanceConfig "name" $.Values.global.name }}
        {{- else }}
          {{- $_ := set $instanceConfig "name" $instanceName }}
        {{- end }}
      {{- end }}
---
      {{- include "mintel_common.workspaceOutputSecret" (list $ . $instanceConfig $resourceType ) }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
