# List the supported resource types here. These should map directly to the top-level fields of the same name in the
# values.yaml file.
{{- range include "mintel_common.terraformCloudResources" $ | split "," }}
  {{- $global := $.Values.global }}
  # Get the config for the current resource in the loop (e.g. resourceType = "memcached", resourceConfig = everything
  # inside the memcached dict in values.yaml)
  {{- $resourceType := . }}
  {{- $resourceConfig := (get $.Values .) }}
  # Create the Workspace CRD only if the enabled field is set to true
  {{- if $resourceConfig.enabled }}
    # Loop through the instances configured in memcached.terraform.instances (create an empty dict with a "default"
    # instance if it hasn't been specified)
    {{- range $instanceName, $instanceConfig := default ( dict "default" dict ) $resourceConfig.terraform.instances }}
      {{- $moduleSource := $resourceConfig.terraform.module.source }}
      {{- $moduleVersion := $resourceConfig.terraform.module.version }}
      {{- $tfVersion := $resourceConfig.terraform.terraformVersion}}
      # Set instance.name via helper
      {{- $instanceDict := dict "Global" $global "InstanceCfg" $instanceConfig "InstanceName" $instanceName "ResourceType" $resourceType }}
      {{- $_ := set $instanceConfig "name" (include "mintel_common.terraform_cloud.instanceConfigName" $instanceDict | trim)}}
      # Set instance.db_name for postgresql and mariadb if not provided
      {{- if ( and ( has $resourceType (list "postgresql" "mariadb") ) ( not ( hasKey $instanceConfig "db_name" ) ) ) }}
        {{- $_ := set $instanceConfig "db_name" ( $instanceConfig.name | snakecase ) }}
      {{- end }}
      # Apply defaults based on environment
      {{- $instanceConfig = mergeOverwrite $instanceConfig (include "mintel_common.terraform_cloud.defaultVarValues" $instanceDict | fromJson ) }}
      {{- if not (hasKey $instanceConfig "aws_account_name") }}
        {{- $_ := set $instanceConfig "aws_account_name" $global.clusterEnv }}
      {{ end }}
      {{- if not (hasKey $instanceConfig "aws_region") }}
        {{- $_ := set $instanceConfig "aws_region" $global.clusterRegion }}
      {{ end }}
      {{- if not (hasKey $instanceConfig "eks_cluster_name") }}
        {{- $_ := set $instanceConfig "eks_cluster_name" $global.clusterName }}
      {{ end }}
      {{- if not (hasKey $instanceConfig "output_secret_name") }}
        {{- $_ := set $instanceConfig "output_secret_name" ( printf "%s/%s/%s" $.Release.Namespace $instanceConfig.name $resourceType ) }}
      {{ end }}
      {{- if not (hasKey $instanceConfig "secret_tags") }}
        {{- $_ := set $instanceConfig "secret_tags" (dict "key" "secret_tags" "value" (printf "{access-project = \"%s-ops\"}" $.Release.Namespace ) "hcl" true) }}
      {{- end }}
      {{- if not (hasKey $instanceConfig "tags") }}
        {{- $_ := set $instanceConfig "tags" (dict "key" "tags" "value" (printf "{\n  Owner       = \"%s\"\n  Project     = \"%s\"\n  Application = \"%s\"\n}" $global.owner $global.partOf $global.name ) "hcl" true) }}
      {{ end }}
      {{- if not (hasKey $instanceConfig "tfcloud_agent") }}
        {{- $_ := set $instanceConfig "tfcloud_agent" "true" }}
      {{ end }}
      # Add default values to each instance if keys not set already
      {{- range $defaultKey, $defaultVal := $resourceConfig.terraform.defaultVars }}
        {{- if not ( hasKey $instanceConfig $defaultKey ) }}
          {{- $_ := set $instanceConfig $defaultKey $defaultVal }}
        {{- end }}
      {{- end }}
      # Create the CRD
---
      {{- include "mintel_common.terraform_cloud.workspace" (list $ . $instanceConfig $resourceType $moduleSource $moduleVersion $tfVersion) }}
    {{- end }}
  {{- end }}
{{- end }}
