{{- define "mintel_common.workspaceOutputSecret" }}
{{- $ := index . 0 }}
{{- $instanceConfig := index . 2 }}
{{- $resourceType := index . 3 }}
{{- $global := $.Values.global }}
{{- with index . 1 }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: "{{ .name }}-{{ $resourceType | kebabcase }}"
  labels: {{ include "mintel_common.labels" $ | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{ include "mintel_common.commonAnnotations" $ | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - key: {{ $instanceConfig.output_secret_name | quote }}
  refreshInterval: 5m0s
  secretStoreRef:
    name: aws-secrets-manager-local
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- end }}
{{- end }}
