{{- define "mintel_common.terraform_cloud.workspace" }}
{{- $ := index . 0 }}
{{- $instanceCfg := index . 2 }}
{{- $resourceType := index . 3 }}
{{- $moduleSource := index . 4 }}
{{- $moduleVersion := index . 5 }}
{{- $tfVersion := index . 6}}
{{- $resourceCfg := index . 7}}
{{- $global := $.Values.global }}
{{- $workspaceDict := dict "Global" $global "Release" $.Release "InstanceCfg" $instanceCfg "ResourceType" $resourceType }}
{{- with index . 1 }}
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: {{ default (include "mintel_common.terraform_cloud.workspaceName" $workspaceDict | trim | quote) $instanceCfg.workspaceNameOverride }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "mintel_common.labels" $ | nindent 4 }}
    name: {{ printf "%s-%s" ($instanceCfg.name | kebabcase) ($resourceType | kebabcase) | trunc 63 }}
    app.kubernetes.io/name: {{ printf "%s-%s" ($instanceCfg.name | kebabcase) ($resourceType | kebabcase) | trunc 63 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" $ | nindent 4 }}
    {{ include "mintel_common.terraform_cloud.operatorAnnotations" $workspaceDict | nindent 4 }}
    {{- if (eq $resourceType "irsa") }}
    app.mintel.com/altManifestFileSuffix: "{{ $global.name }}-{{ $resourceType | kebabcase }}"
    argocd.argoproj.io/sync-wave: "{{ default -20 (default $resourceCfg.syncWave $instanceCfg.syncWave) }}"
    {{- else }}
    app.mintel.com/altManifestFileSuffix: "{{ $instanceCfg.name }}-{{ $resourceType | kebabcase }}"
    argocd.argoproj.io/sync-wave: "{{ default -40 (default $resourceCfg.syncWave $instanceCfg.syncWave) }}"
    {{- end}}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  agentPoolID: {{ $global.terraform.agentPoolID | quote }}
  module:
    source: {{ $moduleSource | quote }}
    version: {{ $moduleVersion | quote }}
  omitNamespacePrefix: true
  organization: {{ $global.terraform.organization | quote }}
  secretsMountPath: {{ $global.terraform.secretsMountPath | quote }}
  sshKeyID: "mintel-ssh"
  terraformVersion: {{ (default $global.terraform.terraformVersion $tfVersion) | quote }}
  {{- if (eq $resourceType "irsa") }}
  runTriggers:
  {{include "mintel_common.terraform_cloud.irsaRunTriggers" .| indent 4}}
  {{- end}}
  variables:
  {{- $_ := unset $instanceCfg "workspaceNameOverride" }}
  {{- $_ := unset $instanceCfg "workspaceAllowDestroy" }}
  {{- $_ := unset $instanceCfg "workspaceOwner" }}
  {{- $_ := unset $instanceCfg "workspaceTags" }}
  {{- $_ := unset $instanceCfg "outputSecretMap" }}
  {{- $_ := unset $instanceCfg "syncWave" }}
  {{- range $varKey, $varVal := $instanceCfg }}
    {{- if kindIs "map" $varVal}}
      {{- include "mintel_common.terraform_cloud.tfVar" (merge (dict "key" $varKey) $varVal) | indent 2 }}
    {{- else }}
      {{- include "mintel_common.terraform_cloud.tfVar" (dict "key" $varKey "value" $varVal) | indent 2 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}

{{- define "mintel_common.terraform_cloud.tfVar" }}
- key: {{ .key | quote }}
  value: {{ .value | quote }}
  environmentVariable: {{ .environmentVariable | default false}}
  hcl: {{ .hcl | default false }}
  sensitive: {{ .sensitive | default false}}
{{- end }}

{{- define "mintel_common.terraform_cloud.workspaceName"}}
{{printf "%s-%s-%s-%s-%s-%s" .Global.clusterEnv .Global.clusterRegion .Global.clusterName .Release.Namespace (.InstanceCfg.name | kebabcase) (.ResourceType | kebabcase) }}
{{- end -}}


{{- define "mintel_common.terraform_cloud.irsaRunTriggers"}}
{{- range include "mintel_common.terraformCloudResources" $ | split "," }}
  {{- $global := $.Values.global }}
  {{- $resourceType := . }}
  {{- $resourceConfig := (get $.Values .) }}
  {{- if (and $resourceConfig.enabled (has $resourceType (list "opensearch" "s3" "dynamodb" "sns" "sqs")))}}
  {{- range $instanceName, $instanceCfg := default ( dict "default" dict ) $resourceConfig.terraform.instances }}
      # Set instance.name via helper
      {{- $instanceDict := dict "Global" $global "InstanceCfg" $instanceCfg "InstanceName" $instanceName "ResourceType" $resourceType }}
      {{- $_ := set $instanceCfg "name" (include "mintel_common.terraform_cloud.instanceConfigName" $instanceDict | trim)}}
{{- $workspaceDict := dict "Global" $global "Release" $.Release "InstanceCfg" $instanceCfg "ResourceType" $resourceType }}
- sourceableName: {{ default (include "mintel_common.terraform_cloud.workspaceName" $workspaceDict | trim | quote) $instanceCfg.workspaceNameOverride }}
  {{- end }}
  {{- end }}
{{- end}}
{{- end -}}
