{{- define "mintel_common.workspace" }}
{{- $ := index . 0 }}
{{- $instanceCfg := index . 2 }}
{{- $resourceType := index . 3 }}
{{- $moduleSource := index . 4 }}
{{- $moduleVersion := index . 5 }}
{{- $global := $.Values.global }}
{{- with index . 1 }}
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: "{{ $global.clusterEnv }}-{{ $global.clusterRegion }}-{{ $global.clusterName }}-{{ $.Release.Namespace }}-{{ $instanceCfg.name }}-{{ $resourceType | kebabcase }}"
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{ include "mintel_common.labels" $ | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" $ | nindent 4 }}
    {{- if (eq $resourceType "irsa") }}
    app.mintel.com/altManifestFileSuffix: "{{ $global.name }}-{{ $resourceType | kebabcase }}"
    {{- else }}
    app.mintel.com/altManifestFileSuffix: "{{ $instanceCfg.name }}-{{ $resourceType | kebabcase }}"
    {{- end}}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  agentPoolID: {{ $global.terraform.agentPoolID | quote }}
  module:
    source: {{ $moduleSource | quote }}
    version: {{ $moduleVersion | quote }}
  omitNamespacePrefix: true
  organization: {{ $global.terraform.organization | quote }}
  secretsMountPath: {{ $global.terraform.secretsMountPath | quote }}
  sshKeyID: "mintel-ssh"
  terraformVersion: {{ $global.terraform.terraformVersion | quote }}
  variables:
  {{- range $varKey, $varVal := $instanceCfg }}
    {{- if kindIs "map" $varVal}}
      {{- include "mintel_common.tfVar" (merge (dict "key" $varKey) $varVal) | indent 2 }}
    {{- else }}
      {{- include "mintel_common.tfVar" (dict "key" $varKey "value" $varVal) | indent 2 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}

{{- define "mintel_common.tfVar" }}
- key: {{ .key | quote }}
  value: {{ .value | quote }}
  environmentVariable: {{ .environmentVariable | default false}}
  hcl: {{ .hcl | default false }}
  sensitive: {{ .sensitive | default false}}
{{- end }}
