{{- range .Values.externalSecrets }}
{{- $secretData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" $ }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" $secretData }}
  labels: {{ include "mintel_common.labels" $secretData | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" $ | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - key: {{ required ".secretPath required for external secret" .secretPath }}
  refreshInterval: {{ default "5m0s" .refreshIntervalOverride }}
  secretStoreRef:
    name: {{ default "aws-secrets-manager-local" .secretStoreRefOverride }}
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- end }}
