{{- range .Values.extraSecrets }}
{{- $secretData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
{{- if (eq $.Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" $ }}
kind: Secret
metadata:
  name: {{ .nameOverride | default (include "mintel_common.fullname" $secretData) }}
  labels: {{ include "mintel_common.labels" $secretData | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" $ | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{- range (required ".localValues required for local env" .localValues) }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end }}
{{- else }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" $ }}
kind: ExternalSecret
metadata:
  name: {{ .nameOverride | default (include "mintel_common.fullname" $secretData) }}
  labels: {{ include "mintel_common.labels" $secretData | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" $ | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - extract:
        key: {{ .pathOverride | default (printf "%s/%s/%s" $.Release.Namespace (include "mintel_common.fullname" $) .name) }}
  refreshInterval: {{ .refreshIntervalOverride | default "5m0s" }}
  secretStoreRef:
    name: {{ .secretStoreRefOverride | default "aws-secrets-manager-local" }}
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- end }}
{{- end }}
