{{- if .Values.service.enabled }}
{{- $serviceData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
apiVersion: {{ include "common.capabilities.service.apiVersion" . }}
kind: Service
metadata:
  name: {{ default (include "mintel_common.fullname" $serviceData) .Values.service.jobName }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.serviceLabels" . | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- if .Values.service.annotations }}
    {{ toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  selector: {{ default (include "mintel_common.selectorLabels" .) .Values.selectorLabelsOverride | nindent 6 }}
{{- end }}
