{{- if (and .Values.serviceAccount .Values.serviceAccount.create) }}
apiVersion: {{ include "common.capabilities.serviceaccount.apiVersion" . }}
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "mintel_common.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  {{- if (or .Values.serviceAccount.annotations (and .Values.serviceAccount.irsa.enabled (ne .Values.global.clusterEnv "local"))) }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- if .Values.global.terraform.irsa }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.cloudProvider.accountId }}:role/app-iam-{{ .Values.global.clusterName }}-{{ .Release.Namespace }}-{{ coalesce .Values.serviceAccount.irsa.nameOverride .Values.serviceAccount.name (include "mintel_common.fullname" .) }}
    {{- else }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.cloudProvider.accountId }}:role/{{ .Values.global.clusterName }}-{{ .Release.Namespace }}-{{ coalesce .Values.serviceAccount.irsa.nameOverride .Values.serviceAccount.name (include "mintel_common.fullname" .) }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
