{{- if .Values.service.enabled }}
apiVersion: {{ include "common.capabilities.service.apiVersion" . }}
kind: Service
metadata:
  name: {{ include "mintel_common.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.serviceLabels" . | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- if .Values.service.annotations }}
    {{ toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  type: {{ .Values.service.type }}
  selector: {{ .Values.service.selectorLabelsOverride | default (include "mintel_common.selectorLabels" . | fromYaml) | toYaml | nindent 4 }}
{{- end }}
