{{- range .Values.configMaps }}
{{- if .create }}
---
{{- $data := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
apiVersion: {{ include "common.capabilities.configmap.apiVersion" . }}
kind: ConfigMap
metadata:
  name: {{ include "mintel_common.fullname" $data }}
  labels: {{ include "mintel_common.labels" $data | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" $data | nindent 4 }}
    {{ if .argo }}
    {{ include "mintel_common.argoAnnotations" .argo | nindent 4 }}
    {{ end }}
  namespace: {{ $.Release.Namespace }}
data:
  {{- range (required "Configmap content required." .configs) }}
  {{- if contains "\n" .data }}
  {{ .name }}: | {{ .data | nindent 4 }}
  {{- else }}
  {{ .name }}: {{ .data }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
