{{- if (eq .Values.cronjobsOnly false) }}
---
{{- if .Values.statefulset }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
{{- else }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "mintel_common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- if (and .Values.liveness (not .Values.liveness.enabled)) }}
    app.mintel.com/opa-skip-liveness-probe-check.main: "true"
    {{- end }}
    {{- if (and .Values.readiness (not .Values.readiness.enabled)) }}
    app.mintel.com/opa-skip-readiness-probe-check.main: "true"
    {{- end }}
    {{- if (and .Values.filebeatSidecar .Values.filebeatSidecar.enabled) }}
    app.mintel.com/opa-skip-readiness-probe-check.filebeat: "true"
    {{- if (and .Values.filebeatSidecar.metrics .Values.filebeatSidecar.metrics.enabled) }}
    app.mintel.com/opa-skip-readiness-probe-check.beat-exporter: "true"
    app.mintel.com/opa-skip-liveness-probe-check.beat-exporter: "true"
    {{- end }}
    {{- end }}
    {{- if (and .Values.gitSyncSidecar .Values.gitSyncSidecar.enabled) }}
    app.mintel.com/opa-skip-readiness-probe-check.git-sync: "true"
    {{- end }}
    {{- include "mintel_common.k8snotify" . | nindent 4 }}
    {{- $secretListStr := (include "mintel_common.secretList" .) }}
    {{- with $secretListStr }}
    secret.reloader.stakater.com/reload: {{ . }}
    {{- end }}
    {{- $configmapListStr := (include "mintel_common.configmapList" .) }}
    {{- with $configmapListStr }}
    configmap.reloader.stakater.com/reload: {{ . }}
    {{- end }}
    {{- if (or .Values.singleReplicaOnly .allowSingleReplica) }}
    app.mintel.com/opa-allow-single-replica: "true"
    {{- end }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
    {{- if (and .Values.ingress .Values.ingress.enabled) }}
    tier: frontend
    {{- end }}
spec:
  {{- if (eq .Values.statefulset false) }}
  {{- with .Values.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- end }}
  {{- if .Values.singleReplicaOnly }}
  replicas: 1
  {{- else }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels: {{ include "mintel_common.selectorLabels" . | nindent 6 }}
  {{- if .Values.statefulset }}
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ include "mintel_common.fullname" . }}
  {{- else }}
  {{- if .Values.singleReplicaOnly }}
  strategy:
    type: Recreate
  {{- else }}
  strategy:
    {{- with .Values.strategy }}
    {{- if (and (eq .type "RollingUpdate") (or .maxSurge .maxUnavailable)) }}
    rollingUpdate:
      {{- with .maxSurge }}
      maxSurge: {{ . }}
      {{- end }}
      {{- with .maxUnavailable }}
      maxUnavailable: {{ . }}
      {{- end }}
    {{- end }}
    type: {{ default "RollingUpdate" .type }}
    {{- else }}
    type: RollingUpdate
    {{- end }}
  {{- end }}
  {{- end }}
  template:
    metadata:
      {{- if (and .Values.hybridCloud .Values.hybridCloud.enabled) }}
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        {{- if .Values.hybridCloud.upstreamServices }}
        'consul.hashicorp.com/connect-service-upstreams': {{ join "," .Values.hybridCloud.upstreamServices }}
        {{- end }}
      {{- end }}
      labels: {{ include "mintel_common.labels" . | nindent 8 }}
        {{- if (and .Values.ingress .Values.ingress.enabled) }}
        tier: frontend
        {{- end }}
    spec:
      {{- include "mintel_common.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if (and .Values.serviceAccount (or .Values.serviceAccount.create .Values.serviceAccount.name)) }}
      serviceAccountName: {{ default (include "mintel_common.fullname" .) .Values.serviceAccount.name }}
      {{- end }}
      {{- if (ne .Values.global.clusterEnv "local") }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- end }}
      {{- include "mintel_common.topologySpreadConstraints" . | nindent 6 }}
      terminationGracePeriodSeconds: {{ default 30 .Values.terminationGracePeriodSeconds }}
      {{- if (and (gt (.Values.replicas | int) 1) (and .Values.affinity .Values.affinity.enabled)) }}
      affinity:
        {{- if (and .Values.affinity .Values.affinity.specificYaml) }}
        {{- toYaml .Values.affinity.specificYaml | nindent 8 }}
        {{- else }}
        podAntiAffinity:
        {{- if (and .Values.affinity .Values.affinity.podAntiAffinity) }}
        {{- if .Values.affinity.podAntiAffinity.specificYaml }}
        {{- toYaml .Values.affinity.podAntiAffinity.specificYaml | nindent 10 }}
        {{- else }}
        {{- if (or (eq .Values.affinity.podAntiAffinity.zone "hard") (eq .Values.affinity.podAntiAffinity.node "hard")) }}
          requiredDuringSchedulingIgnoredDuringExecution:
            {{- if (eq .Values.affinity.podAntiAffinity.zone "hard") }}
            - labelSelector:
                matchLabels: {{ include "mintel_common.selectorLabels" . | nindent 18 }}
              topologyKey: topology.kubernetes.io/zone
            {{- end }}
            {{- if (eq .Values.affinity.podAntiAffinity.node "hard") }}
            - labelSelector:
                matchLabels: {{ include "mintel_common.selectorLabels" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname
            {{- end }}
        {{- end }}
        {{- if (or (eq .Values.affinity.podAntiAffinity.zone "soft") (eq .Values.affinity.podAntiAffinity.node "soft")) }}
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- if (eq .Values.affinity.podAntiAffinity.zone "soft") }}
            - podAffinityTerm:
                labelSelector:
                  matchLabels: {{ include "mintel_common.selectorLabels" . | nindent 20 }}
                topologyKey: topology.kubernetes.io/zone
              weight: {{ default 100 .Values.affinity.podAntiAffinity.weight }}
            {{- end }}
            {{- if (eq .Values.affinity.podAntiAffinity.node "soft") }}
            - podAffinityTerm:
                labelSelector:
                  matchLabels: {{ include "mintel_common.selectorLabels" . | nindent 20 }}
                topologyKey: kubernetes.io/hostname
              weight: {{ default 100 .Values.affinity.podAntiAffinity.weight }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.extraInitContainers }}
      initContainers:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: main
          image: {{ include "mintel_common.image" . }}
          imagePullPolicy: {{ include "mintel_common.imagePullPolicy" . }}
          {{- with .Values.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: KUBERNETES_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- include "mintel_common.localDevEnv" . | nindent 12 }}
            {{- include "mintel_common.defaultEnv" . | nindent 12 }}
            {{- include "mintel_common.redisEnv" . | nindent 12 }}
            {{- include "mintel_common.mailhogEnv" . | nindent 12 }}
            {{- include "mintel_common.elasticsearchEnv" . | nindent 12 }}
            {{- include "mintel_common.opensearchEnv" . | nindent 12 }}
            {{- include "mintel_common.localstackEnv" . | nindent 12 }}
            {{- include "mintel_common.extraHostsEnv" . | nindent 12 }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if (and .Values.externalSecret .Values.externalSecret.enabled) }}
            {{- if (or (ne .Values.global.clusterEnv "local") (and (eq .Values.global.clusterEnv "local") .Values.externalSecret.localValues)) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultAppSecretName" .) .Values.externalSecret.nameOverride }}
            {{- end }}
            {{- end }}
            {{- if (and .Values.mariadb .Values.mariadb.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultMariadbSecretName" .) .Values.mariadb.secretNameOverride }}
            {{- end }}
            {{- if (and .Values.postgresql .Values.postgresql.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultPostgresqlSecretName" .) .Values.postgresql.secretNameOverride }}
            {{- end }}
            {{- if (and .Values.dynamodb .Values.dynamodb.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultDynamodbSecretName" .) .Values.dynamodb.secretNameOverride }}
            {{- end }}
            {{- if (and .Values.redis .Values.redis.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultRedisSecretName" .) .Values.redis.secretNameOverride }}
            {{- end }}
            {{- if (and .Values.s3 .Values.s3.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultS3SecretName" .) .Values.s3.secretNameOverride }}
            {{- end }}
            {{- if (and .Values.sqs .Values.sqs.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultSqsSecretName" .) .Values.sqs.secretNameOverride }}
            {{- end }}
            {{- if (and .Values.elasticsearch .Values.elasticsearch.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultElasticsearchSecretName" .) .Values.elasticsearch.secretNameOverride }}
            {{- end }}
            {{- if (and .Values.opensearch .Values.opensearch.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultOpensearchSecretName" .) .Values.opensearch.secretNameOverride }}
            {{- end }}
            {{- range .Values.extraSecrets }}
            {{- if (or (ne (hasKey . "includeInMain") true) .includeInMain) }}
            - secretRef:
                name: {{ default (printf "%s-%s" (include "mintel_common.fullname" $) .name) .nameOverride }}
            {{- end }}
            {{- end }}
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.port}}
          ports:
            - containerPort: {{ .Values.port }}
              name: http
            {{- if .Values.hybridCloud.enabled }}
            - containerPort: {{ default "20200" .Values.hybridCloud.metrics.port }}
              name: consul-metrics
            - containerPort: {{ default "20000" .Values.hybridCloud.proxyPort }}
              name: consul-proxy
            {{- end }}
            {{- with .Values.extraPorts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end}}
          {{- if (and .Values.liveness .Values.liveness.enabled) }}
          livenessProbe:
            {{- if .Values.liveness.methodOverride }}
            {{- toYaml .Values.liveness.methodOverride | nindent 12 }}
            {{- else }}
            httpGet:
              path: {{ default "/healthz" .Values.liveness.path }}
              port: {{ default "http" .Values.liveness.port }}
              scheme: {{ default "HTTP" .Values.liveness.scheme }}
            {{- end }}
            initialDelaySeconds: {{ default 0 .Values.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ default 1 .Values.liveness.timeoutSeconds }}
            periodSeconds: {{ default 10 .Values.liveness.periodSeconds }}
          startupProbe:
            {{- if .Values.liveness.methodOverride }}
            {{- toYaml .Values.liveness.methodOverride | nindent 12 }}
            {{- else }}
            httpGet:
              path: {{ default "/healthz" .Values.liveness.path }}
              port: {{ default "http" .Values.liveness.port }}
              scheme: {{ default "HTTP" .Values.liveness.scheme }}
            {{- end }}
            {{- if .Values.liveness.startup }}
            {{- if .Values.liveness.startup.failureThreshold }}
            failureThreshold: {{ .Values.liveness.startup.failureThreshold }}
            {{- else }}
            failureThreshold: 60
            {{- end }}
            {{- if .Values.liveness.startup.periodSeconds }}
            periodSeconds: {{ .Values.liveness.startup.periodSeconds }}
            {{- else }}
            periodSeconds: 5
            {{- end }}
            {{- else }}
            failureThreshold: 60
            periodSeconds: 5
            {{- end }}
          {{- end }}
          {{- if (and .Values.readiness .Values.readiness.enabled) }}
          readinessProbe:
            {{- if .Values.readiness.methodOverride }}
            {{- toYaml .Values.readiness.methodOverride | nindent 12 }}
            {{- else }}
            httpGet:
              path: {{ default "/readiness" .Values.readiness.path }}
              port: {{ default "http" .Values.readiness.port }}
              scheme: {{ default "HTTP" .Values.readiness.scheme }}
            {{- end }}
            initialDelaySeconds: {{ default 0 .Values.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ default 1 .Values.readiness.timeoutSeconds }}
            periodSeconds: {{ default 10 .Values.readiness.periodSeconds }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- include "mintel_common.deployment.lifecycle" . | nindent 10 }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
        {{- if (and .Values.filebeatSidecar .Values.filebeatSidecar.enabled) }}
        - name: filebeat
          {{- if (and .Values.opensearch .Values.opensearch.enabled) }}
          image: docker.elastic.co/beats/filebeat-oss:7.10.2
          {{- else }}
          image: docker.elastic.co/beats/filebeat:7.5.2
          {{- end }}
          args:
            - -e
            - -c
            - /config/filebeat.yml
          env:
            - name: CLUSTER_ENV
              value: {{ .Values.global.clusterEnv }}
            - name: CLUSTER_NAME
              value: ${CLUSTER_NAME}
            {{- include "mintel_common.opensearchEnv" . | nindent 12 }}
          envFrom:
            {{- if (and .Values.elasticsearch .Values.elasticsearch.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultElasticsearchSecretName" .) .Values.opensearch.secretNameOverride }}
            {{- end }}
            {{- if (and .Values.opensearch .Values.opensearch.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultOpensearchSecretName" .) .Values.opensearch.secretNameOverride }}
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: beat-http
          ports:
          - containerPort: 5066
            name: beat-http
          {{- with .Values.filebeatSidecar.resources }}
          resources:
          {{- toYaml . | nindent 14 }}
          {{- end }}
          volumeMounts:
            - mountPath: /config/
              name: {{ include "mintel_common.fullname" . }}-filebeat
        {{- if (and .Values.filebeatSidecar.metrics .Values.filebeatSidecar.metrics.enabled) }}
        - image: index.docker.io/trustpilot/beat-exporter:0.3.0
          name: beat-exporter
          ports:
          - containerPort: 9479
            name: metrics
          {{- with .Values.filebeatSidecar.metrics.resources }}
          resources:
          {{- toYaml . | nindent 14 }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if (and .Values.oauthProxy .Values.oauthProxy.enabled) }}
        {{- $oauthProxyData := dict "Release" .Release "Chart" .Chart "Values" .Values "proxiedService" .Values }}
        {{- include "mintel_common.oauthProxySidecar" $oauthProxyData | nindent 8}}
        {{- end }}

        {{- if (and .Values.gitSyncSidecar .Values.gitSyncSidecar.enabled) }}
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.4.0
          args:
            - --depth=1
            - --add-user
            - --http-bind=0.0.0.0:7000
            - --wait=5
            - --max-sync-failures=-1
            - --repo={{ .Values.gitSyncSidecar.repo }}
            - --branch={{ .Values.gitSyncSidecar.branch }}
            - --root={{ .Values.gitSyncSidecar.root }}
            - --dest={{ .Values.gitSyncSidecar.dest }}
          envFrom:
            - secretRef:
                name: {{ include "mintel_common.fullname" . }}-git-sync
          livenessProbe:
            httpGet:
              path: /
              port: git-sync-http
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 120
          ports:
          - containerPort: 7000
            name: git-sync-http
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.gitSyncSidecar.root }}
              name: {{ include "mintel_common.fullname" . }}-git-sync
      {{- end }}
      volumes:
        {{- if .Values.persistentVolumes }}
        {{- range .Values.persistentVolumes }}
        - name: {{ printf "%s-%s" (include "mintel_common.fullname" $ ) .name }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-%s" (include "mintel_common.fullname" $ ) .name }}
        {{- end }}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if (and .Values.filebeatSidecar .Values.filebeatSidecar.enabled) }}
        - name: {{ include "mintel_common.fullname" . }}-filebeat
          configMap:
            name: {{ include "mintel_common.fullname" . }}-filebeat
        {{- end }}
        {{- if (and .Values.gitSyncSidecar .Values.gitSyncSidecar.enabled) }}
        - name: {{ include "mintel_common.fullname" . }}-git-sync
          emptyDir: {}
        {{- end }}
{{- end }}
