{{- if (and .Values.celery .Values.celery.enabled) }}
{{- if (and .Values.celeryBeat .Values.celeryBeat.enabled) }}
{{- $data := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "celery-beat" }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "mintel_common.fullname" $data }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- if (and .Values.celeryBeat.liveness (not .Values.celeryBeat.liveness.enabled)) }}
    app.mintel.com/opa-skip-liveness-probe-check.main: "true"
    {{- end }}
    {{- if (and .Values.celeryBeat.readiness (not .Values.celeryBeat.readiness.enabled)) }}
    app.mintel.com/opa-skip-readiness-probe-check.main: "true"
    {{- end }}
    {{- include "mintel_common.k8snotify" . | nindent 4 }}
    {{- $secretListStr := (include "mintel_common.secretList" .) }}
    {{- with $secretListStr }}
    secret.reloader.stakater.com/reload: {{ . }}
    {{- end }}
    {{- $configmapListStr := (include "mintel_common.configmapList" .) }}
    {{- with $configmapListStr }}
    configmap.reloader.stakater.com/reload: {{ . }}
    {{- end }}
    app.mintel.com/opa-allow-single-replica: "true"
  labels: {{ include "mintel_common.labels" $data | nindent 4 }}
    {{- if (and .Values.redis .Values.redis.enabled) }}
    app.mintel.com/redis-client: "true"
    {{- end }}
spec:
  {{- with .Values.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  replicas: 1
  selector:
    matchLabels: {{ include "mintel_common.selectorLabels" $data | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {{ include "mintel_common.labels" $data | nindent 8 }}
        {{- if (and .Values.redis .Values.redis.enabled) }}
        app.mintel.com/redis-client: "true"
        {{- end }}
    spec:
      {{- include "mintel_common.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if (and .Values.serviceAccount (or .Values.serviceAccount.create .Values.serviceAccount.name)) }}
      serviceAccountName: {{ default (include "mintel_common.fullname" .) .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: main
          image: {{ coalesce .Values.celeryBeat.image (include "mintel_common.image" .) }}
          imagePullPolicy: {{ include "mintel_common.imagePullPolicy" . }}
          {{- with (coalesce .Values.celeryBeat.command .Values.command) }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with (coalesce .Values.celeryBeat.args .Values.args) }}
          args:
            {{- range $key, $value := . }}
            {{- if $value }}
            - {{ $key }}-{{ $value }}
            {{- else }}
            - {{ $key }}
            {{- end }}
            {{- end }}
          {{- end }}
          env:
            - name: KUBERNETES_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- include "mintel_common.localDevEnv" . | nindent 12 }}
            {{- include "mintel_common.defaultEnv" . | nindent 12 }}
            {{- include "mintel_common.redisEnv" . | nindent 12 }}
            {{- include "mintel_common.mailhogEnv" . | nindent 12 }}
            {{- include "mintel_common.elasticsearchEnv" . | nindent 12 }}
            {{- include "mintel_common.opensearchEnv" . | nindent 12 }}
            {{- include "mintel_common.localstackEnv" . | nindent 12 }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.celeryBeat.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if (and .Values.externalSecret .Values.externalSecret.enabled) }}
            {{- if (or (ne .Values.global.clusterEnv "local") (and (eq .Values.global.clusterEnv "local") .Values.externalSecret.localValues)) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultAppSecretName" .) .Values.externalSecret.nameOverride }}
            {{- end }}
            {{- end }}
            {{- if (and .Values.mariadb .Values.mariadb.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultMariadbSecretName" .) .Values.mariadb.secretNameOverride }}
            {{- end }}
            {{- if (and .Values.redis .Values.redis.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultRedisSecretName" .) .Values.redis.secretNameOverride }}
            {{- end }}
            {{- if (and .Values.elasticsearch .Values.elasticsearch.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultElasticsearchSecretName" .) .Values.elasticsearch.secretNameOverride }}
            {{- end }}
            {{- if (and .Values.opensearch .Values.opensearch.enabled) }}
            - secretRef:
                name: {{ default (include "mintel_common.defaultOpensearchSecretName" .) .Values.opensearch.secretNameOverride }}
            {{- end }}
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.port }}
              name: http
          {{- if (and .Values.celeryBeat.liveness .Values.celeryBeat.liveness.enabled) }}
          livenessProbe:
            {{- if .Values.celeryBeat.liveness.method }}
            {{- toYaml .Values.celeryBeat.liveness.method | nindent 12 }}
            {{- else }}
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            {{- end }}
            initialDelaySeconds: {{ default 0 .Values.celeryBeat.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ default 1 .Values.celeryBeat.liveness.timeoutSeconds }}
          startupProbe:
            {{- if .Values.celeryBeat.liveness.method }}
            {{- toYaml .Values.celeryBeat.liveness.method | nindent 12 }}
            {{- else }}
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            {{- end }}
            {{- if .Values.celeryBeat.liveness.startup }}
            {{- if .Values.celeryBeat.liveness.startup.failureThreshold }}
            failureThreshold: {{ .Values.celeryBeat.liveness.startup.failureThreshold }}
            {{- else }}
            failureThreshold: 60
            {{- end }}
            {{- if .Values.celeryBeat.liveness.startup.periodSeconds }}
            periodSeconds: {{ .Values.celeryBeat.liveness.startup.periodSeconds }}
            {{- else }}
            periodSeconds: 5
            {{- end }}
            {{- else }}
            failureThresold: 60
            periodSeconds: 5
            {{- end }}
          {{- end }}
          {{- if (and .Values.celeryBeat.readiness .Values.celeryBeat.readiness.enabled) }}
          readinessProbe:
            {{- if .Values.celeryBeat.readiness.method }}
            {{- toYaml .Values.celeryBeat.readiness.method | nindent 12 }}
            {{- else }}
            httpGet:
              path: /readiness
              port: http
              scheme: HTTP
            {{- end }}
            initialDelaySeconds: {{ default 0 .Values.celeryBeat.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ default 1 .Values.celeryBeat.readiness.timeoutSeconds }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.celeryBeat.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if (or .Values.volumeMounts .Values.celeryBeat.volumeMounts) }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.celeryBeat.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}
