{{- if (and .Values.celery .Values.celery.enabled) }}
{{- if (and .Values.redis .Values.redis.enabled) }}
{{- if (and .Values.celery.metrics .Values.celery.metrics.enabled) }}
{{- $data := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "celery-exporter" }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "mintel_common.fullname" $data }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    app.mintel.com/opa-skip-readiness-probe-check.main: "true"
    app.mintel.com/opa-allow-single-replica: "true"
    app.mintel.com/opa-skip-security-context-check: "true"
  labels: {{ include "mintel_common.labels" $data | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "mintel_common.selectorLabels" $data | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "mintel_common.labels" $data | nindent 8 }}
    spec:
      {{- include "mintel_common.imagePullSecrets" . | nindent 6 }}
      {{- if (and .Values.serviceAccount (or .Values.serviceAccount.create .Values.serviceAccount.name)) }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "mintel_common.fullname" .) }}
      {{- end }}
      containers:
        - name: main
          image: {{ .Values.celery.metrics.image | default "index.docker.io/ovalmoney/celery-exporter:1.5.1"}}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          args:
            - --transport-options
            - '{"master_name":"mymaster"}'
            - --enable-events
            - --verbose
          env:
            - name: KUBERNETES_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- include "mintel_common.redisEnv" . | nindent 12 }}
            - name: CELERY_EXPORTER_BROKER_URL
              {{- if .Values.redis.tls.enabled }}
              value: 'rediss://:$(REDIS_AUTH_TOKEN)@$(REDIS_PRIMARY_ENDPOINT)/0'
              {{- else }}
              value: 'redis://:$(REDIS_AUTH_TOKEN)@$(REDIS_PRIMARY_ENDPOINT)/0'
              {{- end }}
            - name: CELERY_EXPORTER_NAMESPACE
              value: {{ .Release.Namespace }}
          envFrom:
            - secretRef:
                name: {{ .Values.redis.secretNameOverride | default (include "mintel_common.defaultRedisSecretName" .)}}
          ports:
            - containerPort: 9540
              name: metrics
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 1
          securityContext:
            runAsUser: 1000
          {{- with .Values.celery.metrics.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
