{{- if (and .Values.opensearch .Values.opensearch.enabled) }}
{{- if (and .Values.opensearch.awsEsProxy .Values.opensearch.awsEsProxy.enabled) }}
{{- $data := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "aws-es-proxy" }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "mintel_common.fullname" $data }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    secret.reloader.stakater.com/reload: {{ .Values.opensearch.secretNameOverride | default (include "mintel_common.defaultOpensearchSecretName" .) }}
    app.mintel.com/opa-allow-single-replica: "true"
    app.mintel.com/opa-skip-readiness-probe-check.main: "true"
    app.mintel.com/opa-skip-security-context-check: "true"
  labels: {{ include "mintel_common.labels" $data | nindent 4 }}
spec:
  replicas: {{ .Values.opensearch.awsEsProxy.replicas | default 2 }}
  selector:
    matchLabels: {{ include "mintel_common.selectorLabels" $data | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "mintel_common.labels" $data | nindent 8 }}
    spec:
      {{- include "mintel_common.imagePullSecrets" . | nindent 6 }}
      {{- if (and .Values.serviceAccount (or .Values.serviceAccount.create .Values.serviceAccount.name)) }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "mintel_common.fullname" .) }}
      {{- end }}
      {{- include "mintel_common.topologySpreadConstraints" $data | nindent 6 }}
      containers:
        - name: main
          image: index.docker.io/mintel/aws-es-proxy:v1.3.0_mintel.0.1.0
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          args:
            - -listen=0.0.0.0:9200
            - -endpoint=$(OPENSEARCH_HOST)
            {{- if (eq .Values.global.clusterEnv "local") }}
            - -no-sign-reqs
            {{- end }}
          env:
            - name: KUBERNETES_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: {{ .Values.opensearch.secretNameOverride | default (include "mintel_common.defaultOpensearchSecretName" .) }}
          ports:
            - containerPort: 9200
              name: http
          startupProbe:
            httpGet:
              path: /_cluster/health
              port: http
              scheme: HTTP
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          securityContext:
            runAsUser: 65534
          {{- with .Values.opensearch.awsEsProxy.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}
