{{- if (and .Values.mariadb .Values.mariadb.enabled) }}
{{- if (and .Values.mariadb.client .Values.mariadb.client.enabled) }}
{{- $data := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "mysqlclient" }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "mintel_common.fullname" $data }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    secret.reloader.stakater.com/reload: {{ .Values.mariadb.secretNameOverride | default (include "mintel_common.defaultMariadbSecretName" .) }}
    app.mintel.com/opa-allow-single-replica: "true"
    app.mintel.com/opa-skip-liveness-probe-check.main: "true"
    app.mintel.com/opa-skip-readiness-probe-check.main: "true"
  labels: {{ include "mintel_common.labels" $data | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "mintel_common.selectorLabels" $data | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "mintel_common.labels" $data | nindent 8 }}
    spec:
      {{- include "mintel_common.imagePullSecrets" . | nindent 6 }}
      securityContext:
        runAsUser: 1000
      {{- if (and .Values.serviceAccount (or .Values.serviceAccount.create .Values.serviceAccount.name)) }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "mintel_common.fullname" .) }}
      {{- end }}
      containers:
        - name: main
          image: {{ .Values.mariadb.client.image | default "index.docker.io/mintel/k8s-mysqlclient:0.6.0" }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: KUBERNETES_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: {{ .Values.mariadb.secretNameOverride | default (include "mintel_common.defaultMariadbSecretName" .) }}
          ports:
            - containerPort: 3306
              name: mysql
          {{- with .Values.mariadb.client.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}
