{{- if .Values.entra.enabled }}
apiVersion: entraid.mintel.cloud/v1alpha1
kind: PasswordCredential
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: {{ include "mintel_common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
spec:
  application:
    uniqueName: {{ .Values.entra.uniqueName }}
  displayName: ${CLUSTER_NAME}
  outputSecret:
    name: {{ include "mintel_common.fullname" .}}-ingress-oidc-credentials
{{- end }}
