{{- if .Values.entra.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mintel_common.fullname" . }}-alb-controller-secret
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mintel_common.fullname" . }}-alb-controller-secret
subjects:
- kind: ServiceAccount
  name: aws-load-balancer-controller
  namespace: ingress-controller
{{- end }}
