{{- if .Values.ingress.enabled }}
{{- if (eq .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "mintel_common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- if .Values.ingress.extraAnnotations }}
    {{- toYaml .Values.ingress.extraAnnotations | nindent 4 }}
    {{- end}}
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ .Values.ingress.defaultHost }}
      http:
        paths:
          {{- if (eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1beta1") }}
          - path: /
            backend:
              serviceName: {{ include "mintel_common.fullname" . }}
              {{- if (and .Values.oauthProxy .Values.oauthProxy.enabled) }}
              servicePort: 4180
              {{- else }}
              servicePort: {{ .Values.port }}
              {{- end }}
          {{- else }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mintel_common.fullname" . }}
                port:
                  {{- if (and .Values.oauthProxy .Values.oauthProxy.enabled) }}
                  number: 4180
                  {{- else }}
                  number: {{ .Values.port }}
                  {{- end }}
          {{- end }}
{{- else }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "mintel_common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- if .Values.ingress.extraAnnotations }}
    {{- toYaml .Values.ingress.extraAnnotations | nindent 4 }}
    {{- end}}
    
    {{- if (eq (include "mintel_common.ingressClassName" .) "haproxy" ) }}
    {{- with .Values.ingress.serverTimeoutSeconds }}
    ingress.kubernetes.io/timeout-server: {{ . }}
    {{- end }}
    ingress.kubernetes.io/rewrite-target: /
    {{- if (and .Values.metrics .Values.metrics.enabled) }}
    ingress.kubernetes.io/config-backend: |
      acl k8s-monitoring-endpoints path {{ include "mintel_common.ingressDenyEndpoints" . }}
      http-request deny if k8s-monitoring-endpoints
    {{- end }}
    {{- else }}

    {{- if (and .Values.ingress.alb .Values.ingress.alb.enabled) }}
    {{- with .Values.ingress.alb }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-group-attributes: "deregistration_delay.timeout_seconds={{ default 10 .deregistrationDelay.timeoutSeconds }}"
    alb.ingress.kubernetes.io/target-type: "ip"
    external-dns.alpha.kubernetes.io/ttl: "60"
    external-dns.alpha.kubernetes.io/hostname: {{ $.Values.ingress.defaultHost }}
    alb.ingress.kubernetes.io/backend-protocol: {{ include "mintel_common.ingress.alb.backendProtocol" . }}
    alb.ingress.kubernetes.io/backend-protocol-version: {{ include "mintel_common.ingress.alb.backendProtocolVersion" . }}
    alb.ingress.kubernetes.io/success-codes: "{{ include "mintel_common.ingress.alb.healthcheck.successCodes" . }}"
    alb.ingress.kubernetes.io/healthcheck-path: {{ include "mintel_common.ingress.alb.healthcheck.path" . }}
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "{{ default 15 .healthcheck.intervalSeconds }}"
    alb.ingress.kubernetes.io/healthcheck-port: "{{ default $.Values.port .healthcheck.port }}"
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ include "mintel_common.ingress.alb.healthcheck.protocol" . }}
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "{{ default 5 .healthcheck.timeoutSeconds }}"
    alb.ingress.kubernetes.io/healthy-threshold-count: "{{ default 2 .healthcheck.healthyThresholdCount }}"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "{{ default 2 .healthcheck.unhealthyThresholdCount }}"
    {{- end }}
    {{- end }}

    {{- end }}
    {{- if (and .Values.ingress.blackbox .Values.ingress.blackbox.enabled) }}
    prometheus.io/probe: "true"
    prometheus.io/probepath: {{ .Values.ingress.blackbox.probePath }}
    {{- end }}
    {{- if (eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1beta1") }}
    kubernetes.io/ingress.class: {{ include "mintel_common.ingressClassName" . }}
    {{- end }}
spec:
  {{- if (ne (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1beta1") }}
  ingressClassName: {{ include "mintel_common.ingressClassName" . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.defaultHost }}
      http:
        paths:
          {{- if (eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1beta1") }}
          - path: /
            backend:
              serviceName: {{ include "mintel_common.fullname" . }}
              {{- if (and .Values.oauthProxy .Values.oauthProxy.enabled) }}
              servicePort: 4180
              {{- else }}
              servicePort: {{ .Values.port }}
              {{- end }}
          {{- else }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mintel_common.fullname" . }}
                port:
                  {{- if (and .Values.oauthProxy .Values.oauthProxy.enabled) }}
                  number: 4180
                  {{- else }}
                  number: {{ .Values.port }}
                  {{- end }}
          {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          {{- if (eq (include "common.capabilities.ingress.apiVersion" $) "networking.k8s.io/v1beta1") }}
          - path: /
            backend:
              serviceName: {{ default (include "mintel_common.fullname" $) .serviceName }}
              {{- if (and $.Values.oauthProxy $.Values.oauthProxy.enabled) }}
              servicePort: 4180
              {{- else }}
              servicePort: {{ default $.Values.port .servicePort }}
              {{- end }}
          {{- else }}
          - path: {{ default "/" .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ default (include "mintel_common.fullname" $) .serviceName }}
                port:
                  {{- if (and $.Values.oauthProxy $.Values.oauthProxy.enabled) }}
                  number: 4180
                  {{- else }}
                  number: {{ default $.Values.port .servicePort }}
                  {{- end }}
          {{- end }}
    {{- end }}
    {{- with .Values.ingress.specificRulesHostsYaml }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if and .Values.ingress.tls ( or .Values.global.ingressTLSSecrets .Values.ingress.specificTlsHostsYaml ) }}
  tls:
    {{- range $key, $val := .Values.global.ingressTLSSecrets }}
    {{- $domainUsed := false -}}
    {{- $domainHosts := list -}}
    {{- if hasSuffix ($key | replace "_" ".") $.Values.ingress.defaultHost -}}
    {{- $domainUsed = true -}}
    {{- $domainHosts = append $domainHosts $.Values.ingress.defaultHost -}}
    {{- end -}}
    {{- range $.Values.ingress.extraHosts -}}
    {{- if hasSuffix ($key | replace "_" ".") .name -}}
    {{- $domainUsed = true -}}
    {{- $domainHosts = append $domainHosts .name -}}
    {{- end -}}
    {{- end -}}
    {{- if $domainUsed }}
    - hosts:
        {{- toYaml $domainHosts | nindent 8 }}
      secretName: {{ $val }}
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.specificTlsHostsYaml }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
