{{- if .Values.ingress.enabled }}
{{- if (eq .Values.global.clusterEnv "local") }}
---
{{- $ingressData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "ingress" .Values.ingress }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "mintel_common.ingressName" $ingressData }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.ingressLabels" $ingressData | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- if .Values.ingress.extraAnnotations }}
    {{- toYaml .Values.ingress.extraAnnotations | nindent 4 }}
    {{- end }}
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ .Values.ingress.defaultHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mintel_common.fullname" . }}
                port:
                  {{- if (and .Values.oauthProxy .Values.oauthProxy.enabled) }}
                  number: 4180
                  {{- else }}
                  number: {{ .Values.port }}
                  {{- end }}
{{- else }}
{{- $ingresses := prepend .Values.ingress.extraIngresses .Values.ingress -}}
{{- range $ingresses }}
---
{{- $ingressData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "ingress" . }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" $ }}
kind: Ingress
metadata:
  name: {{ include "mintel_common.ingressName" $ingressData }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "mintel_common.ingressLabels" $ingressData | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" $ingressData | nindent 4 }}
    {{- if (or $.Values.ingress.extraAnnotations $ingressData.ingress.extraAnnotations) }}
    {{- $ingressData.extraAnnotations | default $.Values.ingress.extraAnnotations | toYaml | nindent 4 }}
    {{- end }}

    {{- if (eq (include "mintel_common.ingress.className" $ingressData) "haproxy" ) }}
    {{- include "mintel_common.ingress.haproxy_annotations" $ingressData | nindent 4 }}
    {{- else }}

    {{- if (and $.Values.ingress.alb $.Values.ingress.alb.enabled) }}
    {{- $albData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "alb" $.Values.ingress.alb "defaultHost" $ingressData.ingress.defaultHost }}
    {{- include "mintel_common.ingress.alb_annotations" $albData | nindent 4 }}
    {{- end }}

    {{- end }}
    {{- if (and $.Values.ingress.blackbox $.Values.ingress.blackbox.enabled) }}
    prometheus.io/probe: "true"
    prometheus.io/probepath: {{ $.Values.ingress.blackbox.probePath }}
    {{- end }}
spec:
  ingressClassName: {{ include "mintel_common.ingress.className" $ingressData }}
  rules:
    - host: {{ .defaultHost }}
      http:
        paths:
          # 10
          {{- if (not $.Values.ingress.pathBasedRouting) }}
          {{- include "mintel_common.ingress.ingressPath" $ingressData | nindent 10 }}
          {{- else }}
          {{- range $.Values.ingress.pathBasedRouting }}
          {{- $pathData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "targetService" .targetService "targetPort" .targetPort "path" .path "pathType" .pathType }}
          {{- include "mintel_common.ingress.ingressPath" $pathData | nindent 10 }}
          {{- end }}
          {{- end }}
    {{- range .extraHosts }}
    {{- if (or (not $.Values.oauthProxy.enabled) (ne $.Values.oauthProxy.ingressHost .name)) }}
    - host: {{ .name }}
      http:
        paths:
          {{- if (not $.Values.ingress.pathBasedRouting) }}
          {{- $pathData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "targetService" .serviceName "targetPort" .servicePort "path" .path "pathType" .pathType }}
          {{- include "mintel_common.ingress.ingressPath" $pathData | nindent 10 }}
          {{- else }}
          {{- range $.Values.ingress.pathBasedRouting }}
          {{- $pathData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "targetService" .targetService "targetPort" .targetPort "path" .path "pathType" .pathType }}
          {{- include "mintel_common.ingress.ingressPath" $pathData | nindent 10 }}
          {{- end }}
          {{- end }}
    {{- end }}
    {{- end }}
    {{- if (and $.Values.oauthProxy.enabled $.Values.oauthProxy.ingressHost) }}
    - host: {{ $.Values.oauthProxy.ingressHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mintel_common.fullname" $ }}
                port:
                  number: 4180
    {{- end }}
    {{- with $.Values.ingress.specificRulesHostsYaml }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if and $.Values.ingress.tls ( or $.Values.global.ingressTLSSecrets $.Values.ingress.specificTlsHostsYaml ) }}
  tls:
    {{- range $key, $val := $.Values.global.ingressTLSSecrets }}
    {{- $domainUsed := false -}}
    {{- $domainHosts := list -}}
    {{- if hasSuffix ($key | replace "_" ".") $.Values.ingress.defaultHost -}}
    {{- $domainUsed = true -}}
    {{- $domainHosts = append $domainHosts $.Values.ingress.defaultHost -}}
    {{- end -}}
    {{- range $.Values.ingress.extraHosts -}}
    {{- if hasSuffix ($key | replace "_" ".") .name -}}
    {{- $domainUsed = true -}}
    {{- $domainHosts = append $domainHosts .name -}}
    {{- end -}}
    {{- end -}}
    {{- if (and $.Values.oauthProxy $.Values.oauthProxy.ingressHost) }}
    {{- $domainHosts = append $domainHosts $.Values.oauthProxy.ingressHost }}
    {{- end }}
    {{- if $domainUsed }}
    - hosts:
        {{- toYaml $domainHosts | nindent 8 }}
      secretName: {{ $val }}
    {{- end }}
    {{- end }}
    {{- with $.Values.ingress.specificTlsHostsYaml }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}

{{- end }}
{{- end }}
