{{- if .Values.ingress.enabled }}
{{- $apiIsStable := eq (include "common.capabilities.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "common.capabilities.ingress.supportsPathType" .) "true" -}}
{{- if (eq .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "mintel_common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- if not (include "common.capabilities.ingress.supportsIngressClassName" .) }}
    kubernetes.io/ingress.class: traefik
    {{- end }}
spec:
  {{- if (include "common.capabilities.ingress.supportsIngressClassName" .) }}
  ingressClassName: traefik
  {{- end }}
  rules:
    - host: {{ .Values.ingress.defaultHost }}
      http:
        paths:
          - path: /
            {{- if $ingressSupportsPathType }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $apiIsStable }}
              service:
                name: {{ include "mintel_common.fullname" . }}
                port:
                  number: {{ .Values.port }}
              {{- else }}
              serviceName: {{ include "mintel_common.fullname" . }}
              servicePort: {{ .Values.port }}
              {{- end }}
{{- else }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "mintel_common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- if and .Values.ingress.className (not (include "common.capabilities.ingress.supportsIngressClassName" .)) }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- end }}
    {{- with .Values.ingress.serverTimeoutSeconds }}
    ingress.kubernetes.io/timeout-server: {{ . }}s
    {{- end }}
    ingress.kubernetes.io/rewrite-target: /
    {{- if (and .Values.metrics .Values.metrics.enabled) }}
    ingress.kubernetes.io/config-backend: |
      acl k8s-monitoring-endpoints path {{ include "mintel_common.ingressDenyEndpoints" . }}
      http-request deny if k8s-monitoring-endpoints
    {{- if (and .Values.ingress.blackbox .Values.ingress.blackbox.enabled) }}
    prometheus.io/probe: "true"
    prometheus.io/probepath: {{ .Values.ingress.blackbox.probePath }}
    {{- end }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (include "common.capabilities.ingress.supportsIngressClassName" .) }}
  ingressClassName: .Values.ingress.className
  {{- end }}
  rules:
    - host: {{ .Values.ingress.defaultHost }}
      http:
        paths:
          - path: /
            {{- if $ingressSupportsPathType }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $apiIsStable }}
              service:
                name: {{ include "mintel_common.fullname" . }}
                port:
                  number: {{ .Values.port }}
              {{- else }}
              serviceName: {{ include "mintel_common.fullname" . }}
              servicePort: {{ .Values.port }}
              {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ default "Prefix" .pathType }}
            {{- end }}
            backend:
              {{- if $apiIsStable }}
              service:
                name: {{ default (include "mintel_common.fullname" $) .serviceName }}
                port:
                  number: {{ default $.Values.port .servicePort }}
              {{- else }}
              serviceName: {{ default (include "mintel_common.fullname" $) .serviceName }}
              servicePort: {{ default $.Values.port .servicePort }}
              {{- end }}
    {{- end }}
    {{- with .Values.ingress.specificRulesHostsYaml }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range $key, $val := .Values.global.ingressTLSSecrets }}
    {{- $domainUsed := false -}}
    {{- $domainHosts := list -}}
    {{- if hasSuffix ($key | replace "_" ".") $.Values.ingress.defaultHost -}}
    {{- $domainUsed = true -}}
    {{- $domainHosts = append $domainHosts $.Values.ingress.defaultHost -}}
    {{- end -}}
    {{- range $.Values.ingress.extraHosts -}}
    {{- if hasSuffix ($key | replace "_" ".") .name -}}
    {{- $domainUsed = true -}}
    {{- $domainHosts = append $domainHosts .name -}}
    {{- end -}}
    {{- end -}}
    {{- if $domainUsed }}
    - hosts:
        {{- toYaml $domainHosts | nindent 8 }}
      secretName: {{ $val }}
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.specificTlsHostsYaml }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
