{{- if .Values.ingress.enabled }}
{{- if (eq .Values.global.clusterEnv "local") }}
{{- $ingressData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "ingress" .Values.ingress }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "mintel_common.ingressName" $ingressData }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.ingressLabels" $ingressData | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- if .Values.ingress.extraAnnotations }}
    {{- toYaml .Values.ingress.extraAnnotations | nindent 4 }}
    {{- end }}
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ .Values.ingress.defaultHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mintel_common.fullname" . }}
                port:
                  {{- if (and .Values.oauthProxy .Values.oauthProxy.enabled) }}
                  number: 4180
                  {{- else }}
                  number: {{ .Values.port }}
                  {{- end }}
{{- else }}
{{- $rootIngress := omit .Values.ingress "extraIngresses" }}
{{- range prepend .Values.ingress.extraIngresses $rootIngress }}
{{- $ingressData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "ingress" (mergeOverwrite (deepCopy $rootIngress) .) }}
{{- $ingressClass := include "mintel_common.ingress.className" $ingressData }}
{{- with $ingressData.ingress }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" $ }}
kind: Ingress
metadata:
  name: {{ include "mintel_common.ingressName" $ingressData }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "mintel_common.ingressLabels" $ingressData | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" $ingressData | nindent 4 }}

    {{- with .extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

    {{- if (eq $ingressClass "haproxy" ) }}
      {{- include "mintel_common.ingress.haproxy_annotations" $ingressData | nindent 4 }}
    {{- else if .alb.enabled }}
      {{- $albData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "alb" .alb "defaultHost" .defaultHost }}
      {{- include "mintel_common.ingress.alb_annotations" $albData | nindent 4 }}
    {{- end }}

    {{- if (and .blackbox .blackbox.enabled) }}
    prometheus.io/probe: "true"
    prometheus.io/probepath: {{ .blackbox.probePath }}
    {{- end }}
spec:
  ingressClassName: {{ $ingressClass }}
  rules:
    - host: {{ .defaultHost }}
      http:
        paths:
          # 10
          {{- range .pathBasedRouting }}
            {{- $pathData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "targetService" .targetService "targetPort" .targetPort "path" .path "pathType" .pathType }}
            {{- include "mintel_common.ingress.ingressPath" $pathData | nindent 10 }}
          {{- else }}
            {{- include "mintel_common.ingress.ingressPath" $ingressData | nindent 10 }}
          {{- end }}
    {{- range .extraHosts }}
    {{- if (or (not $.Values.oauthProxy.enabled) (ne $.Values.oauthProxy.ingressHost .name)) }}
    - host: {{ .name }}
      http:
        paths:
          {{- range .pathBasedRouting }}
            {{- $pathData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "targetService" .targetService "targetPort" .targetPort "path" .path "pathType" .pathType }}
            {{- include "mintel_common.ingress.ingressPath" $pathData | nindent 10 }}
          {{- else }}
            {{- $pathData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "targetService" .serviceName "targetPort" .servicePort "path" .path "pathType" .pathType }}
            {{- include "mintel_common.ingress.ingressPath" $pathData | nindent 10 }}
          {{- end }}
    {{- end }}
    {{- end }}
    {{- if (and $.Values.oauthProxy.enabled $.Values.oauthProxy.ingressHost) }}
    - host: {{ $.Values.oauthProxy.ingressHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mintel_common.fullname" $ }}
                port:
                  number: 4180
    {{- end }}

    {{- with .specificRulesHostsYaml }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  {{- if and .tls ( or $.Values.global.ingressTLSSecrets .specificTlsHostsYaml ) }}
  tls:
    {{- range $key, $val := $.Values.global.ingressTLSSecrets }}
      {{- $domainUsed := false -}}
      {{- $domainHosts := list -}}
      {{- if hasSuffix ($key | replace "_" ".") $ingressData.ingress.defaultHost -}}
        {{- $domainUsed = true -}}
        {{- $domainHosts = append $domainHosts $ingressData.ingress.defaultHost -}}
      {{- end -}}
      {{- range $ingressData.ingress.extraHosts -}}
        {{- if hasSuffix ($key | replace "_" ".") .name -}}
          {{- $domainUsed = true -}}
          {{- $domainHosts = append $domainHosts .name -}}
        {{- end -}}
      {{- end -}}
      {{- if (and $.Values.oauthProxy $.Values.oauthProxy.ingressHost) }}
        {{- $domainHosts = append $domainHosts $.Values.oauthProxy.ingressHost }}
      {{- end }}
      {{- if $domainUsed }}
    - hosts:
        {{- toYaml $domainHosts | nindent 8 }}
      secretName: {{ $val }}
      {{- end }}
    {{- end }}

    {{- with $ingressData.ingress.specificTlsHostsYaml }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

{{- end }}
{{- end }}

{{- end }}
{{- end }}
