{{- if .Values.ingress.enabled }}
{{- $rootIngress := omit .Values.ingress "extraIngresses" }}
{{- if (eq .Values.global.clusterEnv "local") }}
---
{{ include "mintel_common.ingress" (list $ $rootIngress) }}
{{- else }}
{{- range prepend .Values.ingress.extraIngresses $rootIngress }}
{{- $ingressConfig := mergeOverwrite (deepCopy $rootIngress) . }}
---
{{ include "mintel_common.ingress" (list $ .) }}
{{- end -}}
{{- end -}}
{{- end -}}
