{{- if eq (include "mintel_common.instrumentation.enabled" $) "true" }}
{{- with dict "Release" $.Release "Chart" $.Chart "Values" $.Values "instrumentation" | merge .Values.otelInstrumentation }}
apiVersion: {{ include "common.capabilities.otelInstrumentation.apiVersion" $ }}
kind: Instrumentation
metadata:
  name: {{ include "mintel_common.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "mintel_common.labels" . | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    argocd.argoproj.io/sync-options: 'SkipDryRunOnMissingResource=true'
    argocd.argoproj.io/sync-wave: {{ .syncWave | quote }}
spec:
  exporter:
    endpoint: {{ .exporter.endpoint | quote }}
  {{- with .env }}
  env:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .propagators }}
  propagators:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if .sampler.type }}
  sampler:
    type: {{ .sampler.type | quote }}
    {{- if .sampler.argument }}
    argument: {{ .sampler.argument | quote }}
    {{- end }}
  {{- end }}

  resource:
    resourceAttributes:
      {{- with $.Values.global.cloudProvider.accountId }}
      cloud.account.id: {{ . | quote }}
      {{- end }}
      cloud.platform: aws_eks
      cloud.provider: aws
      {{- with $.Values.global.cloudProvider.region }}
      cloud.region: {{ . | quote }}
      {{- end }}
      {{- with $.Values.global.clusterEnv }}
      deployment.environment: {{ . | quote }}
      {{- end }}
      {{- with $.Values.global.clusterName }}
      k8s.cluster.name: {{ . | quote }}
      {{- end }}
      service.name: {{ include "mintel_common.fullname" . | quote }}
      service.namespace: {{ $.Release.Namespace | quote }}
      {{- with .resource.resourceAttributes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- if .resource.addK8sUIDAttributes }}
    addK8sUIDAttributes: true
    {{- end }}

  {{- if .injectPython.enabled | and .injectSidecar | and (.injectPython.image | or .injectPython.env) }}
  python:
    {{- if .injectPython.image }}
    image: {{ .injectPython.image | quote }}
    {{- end }}
    {{- with .injectPython.env }}
    env:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- if .injectJava.enabled | and (.injectJava.image | or .injectJava.env) }}
  java:
    {{- if .injectJava.image }}
    image: {{ .injectJava.image | quote }}
    {{- end }}
    {{- with .injectJava.env }}
    env:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- if .injectNodeJS.enabled | and (.injectNodeJS.image | or .injectNodeJS.env) }}
  nodejs:
    {{- if .injectNodeJS.image }}
    image: {{ .injectNodeJS.image | quote }}
    {{- end }}
    {{- with .injectNodeJS.env }}
    env:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  {{- if .injectDotNet.enabled | and (.injectDotNet.image | or .injectDotNet.env) }}
  dotnet:
    {{- if .injectDotNet.image }}
    image: {{ .injectDotNet.image | quote }}
    {{- end }}
    {{- with .injectDotNet.env }}
    env:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

{{- end -}}
{{- end }}
