{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkpolicy.apiVersion" . }}
metadata:
  name: {{ include "mintel_common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Values.global.partOf }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/part-of: {{ .Values.global.partOf }}
{{- end }}
