{{- if (and .Values.opensearch .Values.opensearch.enabled) }}
{{- if (and .Values.opensearch.awsEsProxy .Values.opensearch.awsEsProxy.enabled) }}
{{- if (and .Values.opensearch.awsEsProxy.ingress .Values.opensearch.awsEsProxy.ingress.enabled) }}
{{- if (and .Values.opensearch.awsEsProxy.ingress.alb .Values.opensearch.awsEsProxy.ingress.alb.enabled) }}
# We generate this network policy if routing through the public or
# internal ALB to allow Ingress traffic and healthchecks
#
# Healthchecks can be on a different port to the main application port, so
# we allow this to be specified as well.
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkpolicy.apiVersion" . }}
metadata:
  {{- if eq .Values.ingress.alb.scheme "internet-facing" }}
  name: {{ printf "allow-aws-alb-to-%s-opensearch" .Values.global.name }}
  {{- else }}
  # Assume internal facing
  name: {{ printf "allow-aws-alb-internal-to-%s-opensearch" .Values.global.name }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Values.global.partOf }}
  ingress:
    - from:
      {{- if eq .Values.ingress.alb.scheme "internet-facing" }}
      - ipBlock:
          cidr: "${AWS_PUBLIC_SUBNET_CIDR_BLOCKS_0}"
      - ipBlock:
          cidr: "${AWS_PUBLIC_SUBNET_CIDR_BLOCKS_1}"
      - ipBlock:
          cidr: "${AWS_PUBLIC_SUBNET_CIDR_BLOCKS_2}"
      {{- else }}
      # Assume internal facing
      - ipBlock:
          cidr: "${AWS_PRIVATE_APP_SUBNET_CIDR_BLOCKS_0}"
      - ipBlock:
          cidr: "${AWS_PRIVATE_APP_SUBNET_CIDR_BLOCKS_1}"
      - ipBlock:
          cidr: "${AWS_PRIVATE_APP_SUBNET_CIDR_BLOCKS_2}"
      {{- end }}
      ports:
      {{ $ports := list }}
      {{- if .Values.oauthProxy.enabled }}
      {{ $ports = append $ports 4180 }}
      {{- else }}
      {{ $ports = append $ports .Values.opensearch.awsEsProxy.port }}
      {{- end }}
      {{ if .Values.opensearch.awsEsProxy.ingress.alb.healthcheck.port }}
      {{ $ports = append $ports .Values.ingress.alb.healthcheck.port }}
      {{- end }}
      {{ $ports := $ports | sortAlpha | uniq | compact }}
      {{- range $ports }}
        - port: {{ . }}
          protocol: TCP
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
