{{- if (ne .Values.global.clusterEnv "local") }}
{{- if (and .Values.hybridCloud .Values.hybridCloud.enabled) }}
{{- if (and .Values.hybridCloud.metrics .Values.hybridCloud.metrics.enabled) }}
{{- $config := .Values.hybridCloud.metrics | deepCopy }}
{{- if not $config.port }}
{{- $_ := set $config "port" "consul-metrics" }}
{{- end }}
{{- $monitorData := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "consul-proxy" "config" $config "type" "Pod" }}
---
{{ include "mintel_common.monitor" $monitorData }}
{{- end }}
{{- end }}
{{- end }}
