{{- if (ne .Values.global.clusterEnv "local") }}
{{- if (and .Values.mariadb .Values.mariadb.enabled) }}
{{- if (and .Values.mariadb.metrics .Values.mariadb.metrics.enabled) }}

{{- $monitorData := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "mysqldexporter" "config" .Values.mariadb.metrics "type" "Pod" }}
{{ include "mintel_common.monitor" $monitorData }}
{{- end }}
{{- end }}
{{- end }}
