{{- if (eq .Values.service.enabled false) }}
{{- if (ne .Values.global.clusterEnv "local") }}
{{- if (and .Values.metrics .Values.metrics.enabled) }}
---
{{- $monitorData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name "config" $.Values.metrics "type" "Pod" }}
{{ include "mintel_common.monitor" $monitorData }}


{{- range .Values.metrics.additionalMonitors }}
{{- $monitorData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name "config" . "type" "Pod" }}
---
{{ include "mintel_common.monitor" $monitorData }}
{{- end }}
{{- end }}

{{- if (and .Values.oauthProxy .Values.oauthProxy.enabled) }}
{{- $config := dict "port" "auth-proxy-metrics" }}
{{- $monitorData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" "oauth-metrics" "config" $config "type" "Pod" }}
---
{{ include "mintel_common.monitor" $monitorData }}
{{- end }}

{{- if (and .Values.filebeatSidecar .Values.filebeatSidecar.enabled) }}
{{- if (and .Values.filebeatSidecar.metrics .Values.filebeatSidecar.metrics.enabled) }}
{{- $config := dict "port" "beat-exporter-metrics" }}
{{- $filebeatData := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "filebeat" "config" $config "type" "Pod" }}
---
{{ include "mintel_common.monitor" $filebeatData }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
