{{- if (ne .Values.global.clusterEnv "local") }}
{{- if (and .Values.celery .Values.celery.enabled) }}
{{- if (and .Values.redis .Values.redis.enabled) }}
{{- if (and .Values.celery.metrics .Values.celery.metrics.enabled) }}
{{- $data := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "celery-exporter" }}
apiVersion: {{ include "common.capabilities.podmonitor.apiVersion" . }}
kind: PodMonitor
metadata:
  name: {{ include "mintel_common.fullname" $data }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" $data | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissinResource=true
spec:
  podMetricsEndpoints:
    - interval: {{ default "30s" .Values.celery.metrics.interval }}
      path: {{ default "/metrics" .Values.celery.metrics.path }}
      port: metrics
      relabelings:
        - separator: /
          sourceLabels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
          targetLabel: job
      scheme: {{ default "http" .Values.celery.metrics.scheme }}
      scrapeTimeout: {{ default "10s" .Values.celery.metrics.timeout }}
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels: {{ include "mintel_common.selectorLabels" $data | nindent 6 }}
  podTargetLabels: {{ include "mintel_common.podTargetLabelNames" . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
