{{- if (ne .Values.global.clusterEnv "local") }}
{{- if (and .Values.celery .Values.celery.enabled) }}
{{- $targetData := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "celery" }}
{{- if (and .Values.filebeatSidecar .Values.filebeatSidecar.enabled) }}
{{- if (and .Values.filebeatSidecar.metrics .Values.filebeatSidecar.metrics.enabled) }}
{{- $config := .Values.filebeatSidecar.metrics | deepCopy }}
{{- if not $config.port }}
{{- $_ := set $config "port" "beat-exporter-metrics" }}
{{- end }}
{{- $filebeatData := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "celery-filebeat" "config" $config "type" "Pod" }}
---
{{ include "mintel_common.monitor" $filebeatData }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
