{{- if (and .Values.postgresql .Values.postgresql.enabled) }}
{{- if (and .Values.postgresql.extraUsers .Values.postgresql.extraUsers.enabled) }}
---
{{- $data := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
apiVersion: {{ include "common.capabilities.job.apiVersion" $ }}
kind: Job
metadata:
  name: {{ (printf "py-dba-%s-postgresql" (include "mintel_common.fullname" $data)) }}
  labels: {{ include "mintel_common.labels" $data | nindent 4 }}
  annotations:
    {{- include "mintel_common.commonAnnotations" $ | nindent 4 }}
    {{ if .argo }}
    {{ include "mintel_common.argoAnnotations" .argo | nindent 4 }}
    {{ end }}
    argocd.argoproj.io/hook: PreSync
  namespace: {{ $.Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      {{- include "mintel_common.imagePullSecrets" $ | nindent 6 }}
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      serviceAccountName: {{ $.Values.serviceAccount.name | default (include "mintel_common.fullname" $)}}
      restartPolicy: "Never"
      containers:
      - name: main
        image: 551844124467.dkr.ecr.us-east-2.amazonaws.com/gitlab/mintel/satoshi/tools/py-dba:v0.2.0
        imagePullPolicy: IfNotPresent
        env:
        - name: 'LOG_LEVEL'
          value: {{ $.Values.postgresql.extraUsers.job.logLevel }}
        - name: 'CONFIG_FILE'
          value: '/etc/config/py-dba-config'
        - name: DB_ENGINE
          value: postgres
        - name: USER_SECRET_PREFIX
          value: {{ (printf "%s/%s/postgresql" (.Release.Namespace) (include "mintel_common.fullname" .)) }}
        envFrom:
          {{- if (and .Values.postgresql .Values.postgresql.enabled) }}
        - secretRef:
            name: {{ .Values.postgresql.secretNameOverride | default (include "mintel_common.defaultPostgresqlSecretName" .) }}
          {{- end }}
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: {{ (printf "%s-py-dba-config" (include "mintel_common.fullname" .)) }}
---
{{- $data := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
apiVersion: {{ include "common.capabilities.configmap.apiVersion" . }}
kind: ConfigMap
metadata:
  name: {{ (printf "%s-py-dba-config" (include "mintel_common.fullname" .)) }}
  labels: {{ include "mintel_common.labels" $data | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" $data | nindent 4 }}
    {{ if .argo }}
    {{ include "mintel_common.argoAnnotations" .argo | nindent 4 }}
    {{ end }}
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.postgresql.extraUsers.users }}
  py-dba-config: | {{ (printf "users:\n%s" (toYaml .)) | nindent 10 }}
  {{- end }}
{{- end }}
{{- end }}
