{{- if (or (and .Values.ingress.alb.okta .Values.ingress.alb.okta.enabled) (and .Values.opensearch.awsEsProxy.ingress.alb.okta .Values.opensearch.awsEsProxy.ingress.alb.okta.enabled)) }}
{{- $roleData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
---
{{- $roleName := include "mintel_common.okta.alb_controller_role_name" $roleData -}}
{{- $roleBindingConfig := dict "name" $roleName "argo" .argo "roleName" $roleName "serviceAccountName" "aws-load-balancer-controller" "serviceAccountNamespace" "ingress-controller" -}}
{{- include "mintel_common.roleBinding" (list $ $roleBindingConfig) }}
{{- end }}
