{{- if (and .Values.serviceAccount .Values.serviceAccount.create) }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ include "mintel_common.fullname" .  }}
  namespace: {{ .Release.Namespace }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  labels: {{ include "mintel_common.labels" . | nindent 4}}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - create
  - update
{{- end }}
