{{- if (and .Values.externalSecret .Values.externalSecret.enabled) }}
---
{{- if (eq .Values.global.clusterEnv "local") }}
{{- if .Values.externalSecret.localValues }}
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" . }}-app
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range (required ".externalSecret.localValues required for local env" .Values.externalSecret.localValues) }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end }}
{{- end }}
{{- else }}
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" . }}-app
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  backendType: {{ default $.Values.externalSecret.backendType "secretsManager" }}
  dataFrom:
    - {{ coalesce .Values.externalSecret.pathOverride (printf "%s/%s/app" (.Release.Namespace) (include "mintel_common.fullname" .)) }}
{{- end }}
{{- end }}

{{- if (and .Values.mariadb .Values.mariadb.enabled) }}
{{- if (ne .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" . }}-mariadb
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  backendType: {{ default $.Values.externalSecret.backendType "secretsManager" }}
  data:
    {{- $dataKey := ( coalesce .Values.mariadb.secretPathOverride (printf "%s/%s/mariadb" (.Release.Namespace) (include "mintel_common.fullname" .))) }}
    - key: {{ $dataKey }}
      name: DB_HOST
      property: host
    - key: {{ $dataKey }}
      name: DB_NAME
      property: dbname
    - key: {{ $dataKey }}
      name: DB_USER
      property: username
    - key: {{ $dataKey }}
      name: DB_PASSWORD
      property: password
{{- else }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" . }}-mariadb
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_HOST: {{ printf "%s-mariadb" (include "mintel_common.fullname" .) | b64enc }}
  DB_NAME: {{ .Values.mariadb.auth.database | b64enc }}
  DB_USER: {{ .Values.mariadb.auth.username | b64enc }}
  DB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc }}
  mariadb-root-password: {{ .Values.mariadb.auth.password | b64enc }}
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc }}
{{- end }}
{{- end }}

{{- if (and .Values.redis .Values.redis.enabled) }}
{{- if (ne .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" . }}-redis
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  backendType: {{ default $.Values.externalSecret.backendType "secretsManager" }}
  dataFrom:
    - {{ coalesce .Values.redis.secretPathOverride (printf "%s/%s/redis" (.Release.Namespace) (include "mintel_common.fullname" .)) }}
{{- else }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" . }}-redis
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  REDIS_AUTH_TOKEN: {{ (default "test" .Values.redis.auth.password) | b64enc }}
{{- end }}
{{- end }}

{{- if (and .Values.elasticsearch .Values.elasticsearch.enabled) }}
{{- if (ne .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" . }}-elasticsearch
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  backendType: {{ default $.Values.externalSecret.backendType "secretsManager" }}
  dataFrom:
    - {{ coalesce .Values.elasticsearch.secretPathOverride (printf "%s/%s/elasticsearch" (.Release.Namespace) (include "mintel_common.fullname" .)) }}
{{- else }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" . }}-elasticsearch
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ELASTICSEARCH_HOST: {{ printf "%s-elasticsearch-master" (include "mintel_common.fullname" .) | b64enc }}
{{- end }}
{{- end }}
