{{- if (and .Values.externalSecret .Values.externalSecret.enabled) }}
{{- if (eq .Values.global.clusterEnv "local") }}
{{- if .Values.externalSecret.localValues }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" . }}-app
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range (required ".externalSecret.localValues required for local env" .Values.externalSecret.localValues) }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end }}
{{- end }}
{{- else }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" . }}-app
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - key: {{ coalesce .Values.externalSecret.pathOverride (printf "%s/%s/app" (.Release.Namespace) (include "mintel_common.fullname" .)) }}
  refreshInterval: {{ default "5m0s" .Values.externalSecret.secretRefreshIntervalOverride }}
  secretStoreRef:
    name: {{ default "aws-secrets-manager-default" .Values.externalSecret.secretStoreRefOverride }}
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- end }}
{{- end }}


{{- range .Values.extraSecrets }}
{{- $secretData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
{{- if (eq $.Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" $ }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" $secretData }}
  labels: {{ include "mintel_common.labels" $secretData | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" $ | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{- range (required ".localValues required for local env" .localValues) }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end }}
{{- else }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" $ }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" $secretData }}
  labels: {{ include "mintel_common.labels" $secretData | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" $ | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - key: {{ coalesce .path (printf "%s/%s/%s" $.Release.Namespace (include "mintel_common.fullname" $) .name) }}
  refreshInterval: {{ default "5m0s" .refreshIntervalOverride }}
  secretStoreRef:
    name: {{ default "aws-secrets-manager-default" .secretStoreRefOverride }}
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- end }}
{{- end }}

{{- if (and .Values.mariadb .Values.mariadb.enabled) }}
{{- if (ne .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" . }}-mariadb
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  data:
    {{- $dataKey := ( coalesce .Values.mariadb.secretPathOverride (printf "%s/%s/mariadb" (.Release.Namespace) (include "mintel_common.fullname" .))) }}
    - secretKey: DB_HOST
      remoteRef:
        key: {{ $dataKey }}
        property: host
    - secretKey: DB_NAME
      remoteRef:
        key: {{ $dataKey }}
        property: dbname
    - secretKey: DB_USER
      remoteRef:
        key: {{ $dataKey }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ $dataKey }}
        property: password
  refreshInterval: {{ default "5m0s" .Values.mariadb.secretRefreshIntervalOverride }}
  secretStoreRef:
    name: {{ default "aws-secrets-manager-default" .Values.mariadb.secretStoreRefOverride }}
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- else }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" . }}-mariadb
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_HOST: {{ printf "%s-mariadb" (include "mintel_common.fullname" .) | b64enc }}
  DB_NAME: {{ .Values.mariadb.auth.database | b64enc }}
  DB_USER: {{ .Values.mariadb.auth.username | b64enc }}
  DB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc }}
  mariadb-root-password: {{ .Values.mariadb.auth.password | b64enc }}
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc }}
{{- end }}
{{- end }}

{{- if (and .Values.dynamodb .Values.dynamodb.enabled) }}
{{- if (ne .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" . }}-dynamodb
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  data:
    {{- $dataKey := ( coalesce .Values.dynamodb.secretPathOverride (printf "%s/%s/dynamodb" (.Release.Namespace) (include "mintel_common.fullname" .))) }}
    - secretKey: DYNAMODB_TABLE_NAME
      remoteRef:
        key: {{ $dataKey }}
        property: DYNAMODB_TABLE_NAME
  refreshInterval: {{ default "5m0s" .Values.dynamodb.secretRefreshIntervalOverride }}
  secretStoreRef:
    name: {{ default "aws-secrets-manager-default" .Values.dynamodb.secretStoreRefOverride }}
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- else }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" . }}-dynamodb
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DYNAMODB_TABLE_NAME: {{ printf "%s-dynamodb" (include "mintel_common.fullname" .) | b64enc }}
{{- end }}
{{- end }}

{{- if (and .Values.redis .Values.redis.enabled) }}
{{- if (ne .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" . }}-redis
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - key: {{ coalesce .Values.redis.secretPathOverride (printf "%s/%s/redis" (.Release.Namespace) (include "mintel_common.fullname" .)) }}
  refreshInterval: {{ default "5m0s" .Values.redis.secretRefreshIntervalOverride }}
  secretStoreRef:
    name: {{ default "aws-secrets-manager-default" .Values.redis.secretStoreRefOverride }}
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- else }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" . }}-redis
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  REDIS_PRIMARY_ENDPOINT: {{ printf "%s-redis-headless:6379" (include "mintel_common.fullname" .) | b64enc }}
  REDIS_AUTH_TOKEN: {{ (default "test" .Values.redis.auth.password) | b64enc }}
{{- end }}
{{- end }}

{{- if (and .Values.elasticsearch .Values.elasticsearch.enabled) }}
{{- if (ne .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" . }}-elasticsearch
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - key: {{ coalesce .Values.elasticsearch.secretPathOverride (printf "%s/%s/elasticsearch" (.Release.Namespace) (include "mintel_common.fullname" .)) }}
  data:
    {{- $dataKey := ( coalesce .Values.elasticsearch.secretPathOverride (printf "%s/%s/elasticsearch" (.Release.Namespace) (include "mintel_common.fullname" .))) }}
    - secretKey: ES_HOSTS
      remoteRef:
        key: {{ $dataKey }}
        property: ELASTICSEARCH_HOST
  refreshInterval: {{ default "5m0s" .Values.elasticsearch.secretRefreshIntervalOverride }}
  secretStoreRef:
    name: {{ default "aws-secrets-manager-default" .Values.elasticsearch.secretStoreRefOverride }}
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- else }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" . }}-elasticsearch
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ELASTICSEARCH_HOST: {{ printf "%s-elasticsearch-master-headless" (include "mintel_common.fullname" .) | b64enc }}
  ES_HOSTS: {{ printf "%s-elasticsearch-master-headless" (include "mintel_common.fullname" .) | b64enc }}
{{- end }}
{{- end }}

{{- if (and .Values.opensearch .Values.opensearch.enabled) }}
{{- if (ne .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" . }}-opensearch
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - key: {{ coalesce .Values.opensearch.secretPathOverride (printf "%s/%s/opensearch" (.Release.Namespace) (include "mintel_common.fullname" .)) }}
  data:
    {{- $dataKey := ( coalesce .Values.opensearch.secretPathOverride (printf "%s/%s/opensearch" (.Release.Namespace) (include "mintel_common.fullname" .))) }}
    {{- if (not .Values.opensearch.awsEsProxy.enabled) }}
    - secretKey: ES_HOSTS
      remoteRef:
        key: {{ $dataKey }}
        property: OPENSEARCH_HOST
    {{- end }}
    - secretKey: ELASTICSEARCH_HOST
      remoteRef:
        key: {{ $dataKey }}
        property: OPENSEARCH_HOST
  refreshInterval: {{ default "5m0s" .Values.opensearch.secretRefreshIntervalOverride }}
  secretStoreRef:
    name: {{ default "aws-secrets-manager-default" .Values.opensearch.secretStoreRefOverride }}
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- else }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" . }}-opensearch
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ELASTICSEARCH_HOST: {{ printf "http://opensearch-cluster-master-headless:5601" | b64enc }}
  {{- if (not .Values.opensearch.awsEsProxy.enabled) }}
  ES_HOSTS: {{ printf "http://opensearch-cluster-master-headless:5601" | b64enc }}
  {{- end }}
  OPENSEARCH_HOST: {{ printf "http://opensearch-cluster-master-headless:5601" | b64enc }}
  OPENSEARCH_DASHBOARD_HOST: {{ printf "%s-opensearch-dashboards" (include "mintel_common.fullname" .) | b64enc }}
{{- end }}
{{- end }}

{{- if (and .Values.postgresql .Values.postgresql.enabled) }}
{{- if (ne .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ include "mintel_common.fullname" . }}-postgresql
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  data:
    {{- $dataKey := ( coalesce .Values.postgresql.secretPathOverride (printf "%s/%s/postgres" (.Release.Namespace) (include "mintel_common.fullname" .))) }}
    - secretKey: DB_HOST
      remoteRef:
        key: {{ $dataKey }}
        property: host
    - secretKey: DB_NAME
      remoteRef:
        key: {{ $dataKey }}
        property: dbname
    - secretKey: DB_USER
      remoteRef:
        key: {{ $dataKey }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ $dataKey }}
        property: password
    - secretKey: DB_PORT
      remoteRef:
        key: {{ $dataKey }}
        property: port
  refreshInterval: {{ default "5m0s" .Values.postgresql.secretRefreshIntervalOverride }}
  secretStoreRef:
    name: {{ default "aws-secrets-manager-default" .Values.postgresql.secretStoreRefOverride }}
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- else }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  name: {{ include "mintel_common.fullname" . }}-postgresql
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_HOST: {{ printf "%s-postgresql" (include "mintel_common.fullname" .) | b64enc }}
  DB_NAME: {{ .Values.postgresql.auth.database | b64enc }}
  DB_USER: {{ .Values.postgresql.auth.username | b64enc }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  DB_PORT: {{ ( default "5432" .Values.postgresql.auth.port ) | b64enc }}
  postgresql-postgres-password: {{ .Values.postgresql.auth.password | b64enc }}
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc }}
{{- end }}
{{- end }}

{{- if (and .Values.oauthProxy .Values.oauthProxy.enabled) }}
{{- if (ne .Values.global.clusterEnv "local") }}
---
apiVersion: {{ include "common.capabilities.externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  {{- if .Values.oauthProxy.secretNameOverride }}
  name: {{ .Values.oauthProxy.secretNameOverride }}
  {{- else if .Values.oauthProxy.secretSuffix }}
  name: {{ printf "%s-%s" (include "mintel_common.fullname" .) .Values.oauthProxy.secretSuffix }}
  {{- else }}
  name: {{ printf "%s-oauth" (include "mintel_common.fullname" .) }}
  {{- end }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - key: {{ coalesce .Values.oauthProxy.secretPathOverride (printf "%s/%s/oauth" (.Release.Namespace) (include "mintel_common.fullname" .)) }}
  refreshInterval: {{ default "5m0s" .Values.oauthProxy.secretRefreshIntervalOverride }}
  secretStoreRef:
    name: {{ default "aws-secrets-manager-default" .Values.oauthProxy.secretStoreRefOverride }}
    kind: SecretStore
  target:
    creationPolicy: Owner
{{- else }}
---
apiVersion: {{ include "common.capabilities.secret.apiVersion" . }}
kind: Secret
metadata:
  {{- if .Values.oauthProxy.secretNameOverride }}
  name: {{ .Values.oauthProxy.secretNameOverride }}
  {{- else if .Values.oauthProxy.secretSuffix }}
  name: {{ printf "%s-%s" (include "mintel_common.fullname" .) .Values.oauthProxy.secretSuffix }}
  {{- else }}
  name: {{ printf "%s-oauth" (include "mintel_common.fullname" .) }}
  {{- end }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range (required ".Values.oauthProxy.localSecretValues required for local env" .Values.oauthProxy.localSecretValues) }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
