{{- if (and .Values.serviceAccount .Values.serviceAccount.create) }}

{{- range .Values.serviceAccount.clusterRoles }}
{{- $roleData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" $ }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "mintel_common.fullname" $roleData }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "mintel_common.labels" $roleData | nindent 4 }}
  annotations: {{ include "mintel_common.commonAnnotations" $roleData | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mintel_common.fullname" $roleData }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.serviceAccount.name | default (include "mintel_common.fullname" $) }}
    apiGroup: ""
    namespace: {{ $.Release.Namespace }}
  {{- end }}

{{- end }}
