{{- if (and .Values.serviceAccount .Values.serviceAccount.create) }}

{{- if (and .Values.kubelock .Values.kubelock.enabled) }}
---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ include "mintel_common.fullname" .  }}
  namespace: {{ .Release.Namespace }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  labels: {{ include "mintel_common.labels" . | nindent 4}}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - create
  - update
{{- end }}

{{- range .Values.serviceAccount.roles }}
{{- $roleData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" $ }}
kind: Role
metadata:
  name: {{ include "mintel_common.fullname" $roleData }}
  namespace: {{ $.Release.Namespace }}
  annotations: {{ include "mintel_common.commonAnnotations" $roleData | nindent 4 }}
  labels: {{ include "mintel_common.labels" $roleData | nindent 4 }}
rules:
  {{- range .rules }}
  - apiGroups: {{ toYaml .apiGroups | nindent 6 }}
    resources: {{ toYaml .resources | nindent 6 }}
    verbs: {{ toYaml .verbs | nindent 6 }}
  {{- end }}
{{- end }}

{{- end }}
