{{- if and .Values.service.enabled (eq .Values.cronjobsOnly false) }}
apiVersion: {{ include "common.capabilities.service.apiVersion" . }}
kind: Service
metadata:
  name: {{ include "mintel_common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.serviceLabels" . | nindent 4 }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    {{- if .Values.service.annotations }}
    {{ toYaml .Values.service.annotations | nindent 4 }}
    {{ toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
    {{- if (and .Values.global.owner (and .Values.ingress.enabled .Values.ingress.alb.enabled)) }}
    'alb.ingress.kubernetes.io/tags': 'Owner={{ .Values.global.owner }}'
    {{- end }}
    {{- if .Values.nlb.enabled }}
    {{ include "mintel_common.nlb.annotations" . | nindent 4 }}
    {{- end }}
spec:
  ports:
    - name: main-http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      {{- if .Values.nlb.enabled }}
      protocol: TCP
      {{- end }}
    {{- if (and .Values.oauthProxy .Values.oauthProxy.enabled) }}
    - name: auth-proxy-auth-proxy
      port: 4180
      targetPort: 4180
    - name: auth-proxy-metrics
      port: 9090
      targetPort: 9090
    {{- end }}
    {{- if (and .Values.filebeatSidecar .Values.filebeatSidecar.enabled) }}
    {{- if (and .Values.filebeatSidecar.metrics .Values.filebeatSidecar.metrics.enabled) }}
    - name: beat-exporter-metrics
      port: 9479
      targetPort: 9479
    {{- end }}
    {{- end }}
    {{- range .Values.extraPorts }}
    - name: {{ .containerName | default "main" }}-{{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
    {{- end }}
  selector: {{ include "mintel_common.selectorLabels" . | nindent 6 }}
  {{- if .Values.nlb.enabled }}
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
{{- end }}
