{{- if (and .Values.serviceAccount .Values.serviceAccount.create) }}

{{- range .Values.serviceAccount.roles }}
{{- $roleData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" $ }}
kind: Role
metadata:
  name: {{ include "mintel_common.fullname" $roleData }}
  namespace: {{ $.Release.Namespace }}
  annotations: {{ include "mintel_common.commonAnnotations" $roleData | nindent 4 }}
  labels: {{ include "mintel_common.labels" $roleData | nindent 4 }}
rules:
  {{ toYaml .rules | nindent 2 }}
{{- end }}

{{- end }}
