{{- if (and .Values.serviceAccount .Values.serviceAccount.create) }}

{{- range .Values.serviceAccount.clusterRoles }}
{{- $roleData := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
---
apiVersion: {{ include "common.capabilities.rba.apiVersion" $ }}
kind: ClusterRole
metadata:
  name: {{ include "mintel_common.fullname" $roleData }}
  annotations: {{ include "mintel_common.commonAnnotations" $roleData | nindent 4 }}
  labels: {{ include "mintel_common.labels" $roleData | nindent 4 }}
rules:
  {{- range .rules }}
  - apiGroups: {{ toYaml .apiGroups | nindent 6 }}
    resources: {{ toYaml .resources | nindent 6 }}
    verbs: {{ toYaml .verbs | nindent 6 }}
  {{- end }}
{{- end }}

{{- end }}
