{{- if (and .Values.opensearch .Values.opensearch.enabled) }}
{{- $data := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "aws-es-proxy" }}
apiVersion: {{ include "common.capabilities.service.apiVersion" . }}
kind: Service
metadata:
  name: {{ include "mintel_common.fullname" $data }}
  namespace: {{ .Release.Namespace }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  labels: {{ include "mintel_common.labels" $data | nindent 4 }}
spec:
  ports:
    - name: main-http
      port: {{ .Values.opensearch.awsEsProxy.port }}
      targetPort: {{ .Values.opensearch.awsEsProxy.port }}
    {{- if (and .Values.opensearch.awsEsProxy.oauthProxy.enabled (ne .Values.global.clusterEnv "local")) }}
    - name: auth-proxy-auth-proxy
      port: 4180
      targetPort: 4180
    - name: auth-proxy-metrics
      port: 9090
      targetPort: 9090
    {{- end }}
  selector: {{ include "mintel_common.selectorLabels" $data | nindent 6 }}

{{- if (eq .Values.global.clusterEnv "local") }}
{{- $data := dict "Release" .Release "Chart" .Chart "Values" .Values "component" "aws-es-proxy-dashboards" }}
---
apiVersion: {{ include "common.capabilities.service.apiVersion" . }}
kind: Service
metadata:
  name: {{ include "mintel_common.fullname" $data }}
  namespace: {{ .Release.Namespace }}
  annotations: {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
  labels: {{ include "mintel_common.labels" $data | nindent 4 }}
spec:
  ports:
    - name: main-http
      port: {{ .Values.opensearch.awsEsProxy.port }}
      targetPort: {{ .Values.opensearch.awsEsProxy.port }}
  selector: {{ include "mintel_common.selectorLabels" $data | nindent 6 }}
{{- end }}
{{- end }}
