# Default values for terraform-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # -- Name of the application
  name: "example-app"
  # -- Team which "owns" the application
  owner: ""
  # -- Top level application each deployment is a part of
  partOf: ""
  # -- Additional labels to apply to all resources
  additionalLabels: {}
  # -- Kubernetes cluster domain
  clusterDomain: "127.0.0.1.nip.io"
  # -- Environment (local, dev, qa, prod)
  clusterEnv: "local"
  # -- Kubernetes cluster name
  clusterName: ""
  # -- Kubernetes cluster region
  clusterRegion: ""
  # -- Global variables relating to cloud provider
  terraform:
    organization: Mintel
    secretsMountPath: /tmp/secrets
    terraformVersion: 1.0.7
    # set to true as part of tf cloud migrations. When true, it stops standard-application-stack from creating AWS related external secrets and passes that responsibility to the terraform-cloud chart
    externalSecrets: true

dynamodb:
  # -- Set to true to create a DynamoDB instance
  enabled: false
  terraform:
    module:
      # -- Registry path of the Terraform module used to create the resource
      # (https://app.terraform.io/app/Mintel/registry/modules/private/Mintel/dynamodb/aws)
      source: app.terraform.io/Mintel/dynamodb/aws
      # -- Module version
      version: "0.1.0-beta.1"
    # -- Vars to be applied to all instances defined
    defaultVars: {}
    # Vars to consider:
    # hash_key
    # range_key
    # attributes

sqs:
  # -- Set to true to create an SQS resource
  enabled: false
  terraform:
    module:
      # -- Registry path of the Terraform module used to create the resource
      # (https://app.terraform.io/app/Mintel/registry/modules/private/Mintel/sqs/aws)
      source: app.terraform.io/Mintel/sqs/aws
      # -- Module version
      version: "0.1.0-beta.1"
    # -- Vars to be applied to all instances defined
    defaultVars: {}

sns:
  # -- Set to true to create an SNS resource
  enabled: false
  terraform:
    module:
      # -- Registry path of the Terraform module used to create the resource
      # (https://app.terraform.io/app/Mintel/registry/modules/private/Mintel/sns/aws)
      source: app.terraform.io/Mintel/sns/aws
      # -- Module version
      version: "0.1.0-beta.1"
    # -- Vars to be applied to all instances defined
    defaultVars: {}

staticWebsite:
  # -- Set to true to create static website (a public bucket and associated resources)
  enabled: false
  terraform:
    module:
      # -- Registry path of the Terraform module used to create the resource
      # (https://app.terraform.io/app/Mintel/registry/modules/private/Mintel/public-static-website/aws)
      source: app.terraform.io/Mintel/public-static-website/aws
      # -- Module version
      version: "0.1.0-beta.1"
    # -- Vars to be applied to all instances defined
    defaultVars: {}
    # Vars to consider:
    # cloudfront_index_document
    # cloudfront_error_responses
    # create_route53_entry

mariadb:
  # -- Set to true to create a MariaDB RDS instance
  enabled: false
  terraform:
    module:
      # -- Registry path of the Terraform module used to create the resource
      # (https://app.terraform.io/app/Mintel/registry/modules/private/Mintel/rds/aws)
      source: app.terraform.io/Mintel/rds/aws
      # -- Module version
      version: "0.1.0-beta.2"
    # -- Vars to be applied to all instances defined
    defaultVars:
      engine: "mariadb"
      engine_version: "10.5"
      port: 3306
    ## Workload resources are generated from the 'instances' map below. If postgresql.enabled is true and
    ## postgresql.terraform.instances is undefined then a default instance will be created with all the values from
    ## postgresql.terraform.defaultVars; "name" and "db_name" will be auto-generated as explained below. Any items added
    ## to an instance will be sent to Terraform Cloud as-is so consult the Terraform module for valid inputs.
    # instances:
    #   "my-instance":
    #     name: if not provided, name will match global.name
    #     db_name: if not provided, db_name will match a snakecase version of global.name (dashes (-) will be converted
    #              to underscores)
    #     any_other_var: will be sent to terraform

memcached:
  # -- Set to true to create a memcached Elasticache resource
  enabled: false
  terraform:
    module:
      # -- Registry path of the Terraform module used to create the resource
      # (https://app.terraform.io/app/Mintel/registry/modules/private/Mintel/memcached/aws)
      source: app.terraform.io/Mintel/memcached/aws
      # -- Module version
      version: "0.1.0-beta.2"
    # -- Vars to be applied to all instances defined
    defaultVars:
      instance_type: cache.t4g.micro
      num_cache_nodes: 1

opensearch:
  # -- Set to true to create an Opensearch cluster
  enabled: false
  terraform:
    module:
      # -- Registry path of the Terraform module used to create the resource
      # (https://app.terraform.io/app/Mintel/registry/modules/private/Mintel/opensearch/aws)
      source: app.terraform.io/Mintel/opensearch/aws
      # -- Module version
      version: "0.1.0-beta.2"
    # -- Vars to be applied to all instances defined
    defaultVars: {}

postgresql:
  # -- Set to true to create a PostgreSQL RDS instance
  enabled: false
  terraform:
    module:
      # -- Registry path of the Terraform module used to create the resource
      # (https://app.terraform.io/app/Mintel/registry/modules/private/Mintel/rds/aws)
      source: app.terraform.io/Mintel/rds/aws
      # -- Module version
      version: "0.1.0-beta.2"
    # -- Vars to be applied to all instances defined
    defaultVars:
      engine: "postgres"
      engine_version: "13"
      port: 5432
    ## Workload resources are generated from the 'instances' map below. If postgresql.enabled is true and
    ## postgresql.terraform.instances is undefined then a default instance will be created with all the values from
    ## postgresql.terraform.defaultVars; "name" and "db_name" will be auto-generated as explained below. Any items added
    ## to an instance will be sent to Terraform Cloud as-is so consult the Terraform module for valid inputs.
    # instances:
    #   "my-instance":
    #     name: if not provided, name will match global.name
    #     db_name: if not provided, db_name will match a snakecase version of global.name (dashes (-) will be converted
    #              to underscores)
    #     any_other_var: will be sent to terraform

redis:
  # -- Set to true to create a Redis Elasticache resource
  enabled: false
  terraform:
    module:
      # -- Registry path of the Terraform module used to create the resource
      # (https://app.terraform.io/app/Mintel/registry/modules/private/Mintel/redis/aws)
      source: app.terraform.io/Mintel/redis/aws
      # -- Module version
      version: "0.1.0-beta.2"
    # -- Vars to be applied to all instances defined
    defaultVars: {}

s3:
  # -- Set to true to create an S3 bucket
  enabled: true
  terraform:
    module:
      # -- Registry path of the Terraform module used to create the resource
      # (https://app.terraform.io/app/Mintel/registry/modules/private/Mintel/private-s3-bucket/aws)
      source: app.terraform.io/Mintel/private-s3-bucket/aws
      # -- Module version
      version: "0.1.0-beta.1"
    # -- Vars to be applied to all instances defined
    defaultVars: {}
