{{- if (ne .Values.global.clusterEnv "local") }}
{{- if (and .Values.metrics .Values.metrics.enabled) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mintel_common.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" . | nindent 4 }}
    k8s-app: {{ include "mintel_common.fullname" . }}
  annotations:
    {{ include "mintel_common.commonAnnotations" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  endpoints:
    - interval: {{ default "30s" .Values.metrics.interval }}
      path: {{ default "/metrics" .Values.metrics.path }}
      port: main-{{ default "http" .Values.metrics.port }}
      {{- if .Values.metrics.basicAuth }}
      {{- if .Values.metrics.basicAuth.enabled }}
      basicAuth:
        username:
          key: {{ .Values.metrics.basicAuth.usernameKey }}
          name: {{ include "mintel_common.defaultAppSecretName" . }}
        password:
          key: {{ .Values.metrics.basicAuth.passwordKey }}
          name: {{ include "mintel_common.defaultAppSecretName" . }}
      {{- end }}
      {{- end }}
      relabelings:
        - separator: /
          sourceLabels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
          targetLabel: job
      scheme: {{ default "http" .Values.metrics.scheme }}
      scrapeTimeout: {{ default "10s" .Values.metrics.timeout }}
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels: {{ include "mintel_common.selectorLabels" . | nindent 6 }}
  targetLabels: {{ include "mintel_common.targetLabelNames" . | nindent 4 }}
  podTargetLabels: {{ include "mintel_common.podTargetLabelNames" . | nindent 4 }}
{{- end }}
{{- end }}
