{{- if .Values.serviceAccount.create -}}
{{- $data := dict "Release" $.Release "Chart" $.Chart "Values" $.Values "component" .name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-api-gateway-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "mintel_common.labels" $data | nindent 4 }}
  annotations:
  {{- include "mintel_common.commonAnnotations" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml . }}
{{- end }}
{{- end -}}
